package com.mapper;

import com.mapper.domain.AdminAppMember;
import com.mapper.domain.AdminAppMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminAppMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_member
     *
     * @mbggenerated
     */
    int countByExample(AdminAppMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_member
     *
     * @mbggenerated
     */
    int deleteByExample(AdminAppMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_member
     *
     * @mbggenerated
     */
    int insert(AdminAppMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_member
     *
     * @mbggenerated
     */
    int insertSelective(AdminAppMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_member
     *
     * @mbggenerated
     */
    AdminAppMember selectOneByExample(AdminAppMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_member
     *
     * @mbggenerated
     */
    List<AdminAppMember> selectByExample(AdminAppMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_member
     *
     * @mbggenerated
     */
    AdminAppMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_member
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AdminAppMember record, @Param("example") AdminAppMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_member
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AdminAppMember record, @Param("example") AdminAppMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminAppMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminAppMember record);

    int updateShareOrderStatusByAccount(@Param("account") String account, @Param("status") Integer status);
}