package com.mapper;

import com.mapper.domain.BonusCategory;
import com.mapper.domain.BonusCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BonusCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_category
     *
     * @mbggenerated
     */
    int countByExample(BonusCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_category
     *
     * @mbggenerated
     */
    int deleteByExample(BonusCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_category
     *
     * @mbggenerated
     */
    int insert(BonusCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_category
     *
     * @mbggenerated
     */
    int insertSelective(BonusCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_category
     *
     * @mbggenerated
     */
    BonusCategory selectOneByExample(BonusCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_category
     *
     * @mbggenerated
     */
    List<BonusCategory> selectByExample(BonusCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_category
     *
     * @mbggenerated
     */
    BonusCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BonusCategory record, @Param("example") BonusCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BonusCategory record, @Param("example") BonusCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BonusCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BonusCategory record);
}