package com.mapper;

import com.mapper.domain.FivesscRecommend;
import com.mapper.domain.FivesscRecommendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FivesscRecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivessc_recommend
     *
     * @mbggenerated
     */
    int countByExample(FivesscRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivessc_recommend
     *
     * @mbggenerated
     */
    int deleteByExample(FivesscRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivessc_recommend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivessc_recommend
     *
     * @mbggenerated
     */
    int insert(FivesscRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivessc_recommend
     *
     * @mbggenerated
     */
    int insertSelective(FivesscRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivessc_recommend
     *
     * @mbggenerated
     */
    FivesscRecommend selectOneByExample(FivesscRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivessc_recommend
     *
     * @mbggenerated
     */
    List<FivesscRecommend> selectByExample(FivesscRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivessc_recommend
     *
     * @mbggenerated
     */
    FivesscRecommend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivessc_recommend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FivesscRecommend record, @Param("example") FivesscRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivessc_recommend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FivesscRecommend record, @Param("example") FivesscRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivessc_recommend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FivesscRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivessc_recommend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FivesscRecommend record);
}