package com.mapper;

import com.mapper.domain.FiveluckpksKillNumber;
import com.mapper.domain.FiveluckpksKillNumberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FiveluckpksKillNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiveluckpks_kill_number
     *
     * @mbggenerated
     */
    int countByExample(FiveluckpksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiveluckpks_kill_number
     *
     * @mbggenerated
     */
    int deleteByExample(FiveluckpksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiveluckpks_kill_number
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiveluckpks_kill_number
     *
     * @mbggenerated
     */
    int insert(FiveluckpksKillNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiveluckpks_kill_number
     *
     * @mbggenerated
     */
    int insertSelective(FiveluckpksKillNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiveluckpks_kill_number
     *
     * @mbggenerated
     */
    FiveluckpksKillNumber selectOneByExample(FiveluckpksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiveluckpks_kill_number
     *
     * @mbggenerated
     */
    List<FiveluckpksKillNumber> selectByExample(FiveluckpksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiveluckpks_kill_number
     *
     * @mbggenerated
     */
    FiveluckpksKillNumber selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiveluckpks_kill_number
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FiveluckpksKillNumber record, @Param("example") FiveluckpksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiveluckpks_kill_number
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FiveluckpksKillNumber record, @Param("example") FiveluckpksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiveluckpks_kill_number
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FiveluckpksKillNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiveluckpks_kill_number
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FiveluckpksKillNumber record);
}