package com.mapper;

import com.mapper.domain.FivepksKillNumber;
import com.mapper.domain.FivepksKillNumberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FivepksKillNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivepks_kill_number
     *
     * @mbggenerated
     */
    int countByExample(FivepksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivepks_kill_number
     *
     * @mbggenerated
     */
    int deleteByExample(FivepksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivepks_kill_number
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivepks_kill_number
     *
     * @mbggenerated
     */
    int insert(FivepksKillNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivepks_kill_number
     *
     * @mbggenerated
     */
    int insertSelective(FivepksKillNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivepks_kill_number
     *
     * @mbggenerated
     */
    FivepksKillNumber selectOneByExample(FivepksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivepks_kill_number
     *
     * @mbggenerated
     */
    List<FivepksKillNumber> selectByExample(FivepksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivepks_kill_number
     *
     * @mbggenerated
     */
    FivepksKillNumber selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivepks_kill_number
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FivepksKillNumber record, @Param("example") FivepksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivepks_kill_number
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FivepksKillNumber record, @Param("example") FivepksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivepks_kill_number
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FivepksKillNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fivepks_kill_number
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FivepksKillNumber record);
}