package com.mapper;

import com.mapper.domain.FtftjspksCountSglh;
import com.mapper.domain.FtftjspksCountSglhExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FtftjspksCountSglhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ftftjspks_count_sglh
     *
     * @mbggenerated
     */
    int countByExample(FtftjspksCountSglhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ftftjspks_count_sglh
     *
     * @mbggenerated
     */
    int deleteByExample(FtftjspksCountSglhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ftftjspks_count_sglh
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ftftjspks_count_sglh
     *
     * @mbggenerated
     */
    int insert(FtftjspksCountSglh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ftftjspks_count_sglh
     *
     * @mbggenerated
     */
    int insertSelective(FtftjspksCountSglh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ftftjspks_count_sglh
     *
     * @mbggenerated
     */
    FtftjspksCountSglh selectOneByExample(FtftjspksCountSglhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ftftjspks_count_sglh
     *
     * @mbggenerated
     */
    List<FtftjspksCountSglh> selectByExample(FtftjspksCountSglhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ftftjspks_count_sglh
     *
     * @mbggenerated
     */
    FtftjspksCountSglh selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ftftjspks_count_sglh
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FtftjspksCountSglh record, @Param("example") FtftjspksCountSglhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ftftjspks_count_sglh
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FtftjspksCountSglh record, @Param("example") FtftjspksCountSglhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ftftjspks_count_sglh
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FtftjspksCountSglh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ftftjspks_count_sglh
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FtftjspksCountSglh record);
}