package com.mapper;

import com.mapper.domain.InstationMessage;
import com.mapper.domain.InstationMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InstationMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instation_message
     *
     * @mbggenerated
     */
    int countByExample(InstationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instation_message
     *
     * @mbggenerated
     */
    int deleteByExample(InstationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instation_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instation_message
     *
     * @mbggenerated
     */
    int insert(InstationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instation_message
     *
     * @mbggenerated
     */
    int insertSelective(InstationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instation_message
     *
     * @mbggenerated
     */
    InstationMessage selectOneByExample(InstationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instation_message
     *
     * @mbggenerated
     */
    List<InstationMessage> selectByExample(InstationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instation_message
     *
     * @mbggenerated
     */
    InstationMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instation_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InstationMessage record, @Param("example") InstationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instation_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InstationMessage record, @Param("example") InstationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instation_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InstationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instation_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InstationMessage record);
}