package com.mapper;

import com.mapper.domain.JsspdpksCountSgdx;
import com.mapper.domain.JsspdpksCountSgdxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsspdpksCountSgdxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsspdpks_count_sgdx
     *
     * @mbggenerated
     */
    int countByExample(JsspdpksCountSgdxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsspdpks_count_sgdx
     *
     * @mbggenerated
     */
    int deleteByExample(JsspdpksCountSgdxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsspdpks_count_sgdx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsspdpks_count_sgdx
     *
     * @mbggenerated
     */
    int insert(JsspdpksCountSgdx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsspdpks_count_sgdx
     *
     * @mbggenerated
     */
    int insertSelective(JsspdpksCountSgdx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsspdpks_count_sgdx
     *
     * @mbggenerated
     */
    JsspdpksCountSgdx selectOneByExample(JsspdpksCountSgdxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsspdpks_count_sgdx
     *
     * @mbggenerated
     */
    List<JsspdpksCountSgdx> selectByExample(JsspdpksCountSgdxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsspdpks_count_sgdx
     *
     * @mbggenerated
     */
    JsspdpksCountSgdx selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsspdpks_count_sgdx
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JsspdpksCountSgdx record, @Param("example") JsspdpksCountSgdxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsspdpks_count_sgdx
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JsspdpksCountSgdx record, @Param("example") JsspdpksCountSgdxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsspdpks_count_sgdx
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JsspdpksCountSgdx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsspdpks_count_sgdx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JsspdpksCountSgdx record);
}