package com.mapper;

import com.mapper.domain.LhcPlaySetting;
import com.mapper.domain.LhcPlaySettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LhcPlaySettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_play_setting
     *
     * @mbggenerated
     */
    int countByExample(LhcPlaySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_play_setting
     *
     * @mbggenerated
     */
    int deleteByExample(LhcPlaySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_play_setting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_play_setting
     *
     * @mbggenerated
     */
    int insert(LhcPlaySetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_play_setting
     *
     * @mbggenerated
     */
    int insertSelective(LhcPlaySetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_play_setting
     *
     * @mbggenerated
     */
    LhcPlaySetting selectOneByExample(LhcPlaySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_play_setting
     *
     * @mbggenerated
     */
    List<LhcPlaySetting> selectByExample(LhcPlaySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_play_setting
     *
     * @mbggenerated
     */
    LhcPlaySetting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_play_setting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LhcPlaySetting record, @Param("example") LhcPlaySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_play_setting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LhcPlaySetting record, @Param("example") LhcPlaySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_play_setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LhcPlaySetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_play_setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LhcPlaySetting record);
}