package com.mapper;

import com.mapper.domain.ManualStartlottoRecord;
import com.mapper.domain.ManualStartlottoRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManualStartlottoRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_startlotto_record
     *
     * @mbggenerated
     */
    int countByExample(ManualStartlottoRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_startlotto_record
     *
     * @mbggenerated
     */
    int deleteByExample(ManualStartlottoRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_startlotto_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_startlotto_record
     *
     * @mbggenerated
     */
    int insert(ManualStartlottoRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_startlotto_record
     *
     * @mbggenerated
     */
    int insertSelective(ManualStartlottoRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_startlotto_record
     *
     * @mbggenerated
     */
    ManualStartlottoRecord selectOneByExample(ManualStartlottoRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_startlotto_record
     *
     * @mbggenerated
     */
    List<ManualStartlottoRecord> selectByExample(ManualStartlottoRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_startlotto_record
     *
     * @mbggenerated
     */
    ManualStartlottoRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_startlotto_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ManualStartlottoRecord record, @Param("example") ManualStartlottoRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_startlotto_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ManualStartlottoRecord record, @Param("example") ManualStartlottoRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_startlotto_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManualStartlottoRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manual_startlotto_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManualStartlottoRecord record);
}