package com.mapper;

import com.mapper.domain.MemberBalanceChange;
import com.mapper.domain.MemberBalanceChangeExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MemberBalanceChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_balance_change
     *
     * @mbggenerated
     */
    int countByExample(MemberBalanceChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_balance_change
     *
     * @mbggenerated
     */
    int deleteByExample(MemberBalanceChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_balance_change
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_balance_change
     *
     * @mbggenerated
     */
    int insert(MemberBalanceChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_balance_change
     *
     * @mbggenerated
     */
    int insertSelective(MemberBalanceChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_balance_change
     *
     * @mbggenerated
     */
    MemberBalanceChange selectOneByExample(MemberBalanceChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_balance_change
     *
     * @mbggenerated
     */
    List<MemberBalanceChange> selectByExample(MemberBalanceChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_balance_change
     *
     * @mbggenerated
     */
    MemberBalanceChange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_balance_change
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemberBalanceChange record, @Param("example") MemberBalanceChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_balance_change
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemberBalanceChange record, @Param("example") MemberBalanceChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_balance_change
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberBalanceChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_balance_change
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberBalanceChange record);

    List<Map<String, Object>> statisticsAllType(@Param("startTime") String startTime,@Param("endTime")String endTime);

}