package com.mapper;

import com.mapper.domain.Operater;
import com.mapper.domain.OperaterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperaterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operater
     *
     * @mbggenerated
     */
    int countByExample(OperaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operater
     *
     * @mbggenerated
     */
    int deleteByExample(OperaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operater
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operater
     *
     * @mbggenerated
     */
    int insert(Operater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operater
     *
     * @mbggenerated
     */
    int insertSelective(Operater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operater
     *
     * @mbggenerated
     */
    Operater selectOneByExample(OperaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operater
     *
     * @mbggenerated
     */
    List<Operater> selectByExample(OperaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operater
     *
     * @mbggenerated
     */
    Operater selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operater
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Operater record, @Param("example") OperaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operater
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Operater record, @Param("example") OperaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operater
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Operater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operater
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Operater record);
}