package com.mapper;

import com.mapper.domain.PasswordFreeze;
import com.mapper.domain.PasswordFreezeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PasswordFreezeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_freeze
     *
     * @mbggenerated
     */
    int countByExample(PasswordFreezeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_freeze
     *
     * @mbggenerated
     */
    int deleteByExample(PasswordFreezeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_freeze
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_freeze
     *
     * @mbggenerated
     */
    int insert(PasswordFreeze record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_freeze
     *
     * @mbggenerated
     */
    int insertSelective(PasswordFreeze record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_freeze
     *
     * @mbggenerated
     */
    PasswordFreeze selectOneByExample(PasswordFreezeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_freeze
     *
     * @mbggenerated
     */
    List<PasswordFreeze> selectByExample(PasswordFreezeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_freeze
     *
     * @mbggenerated
     */
    PasswordFreeze selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_freeze
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PasswordFreeze record, @Param("example") PasswordFreezeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_freeze
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PasswordFreeze record, @Param("example") PasswordFreezeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_freeze
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PasswordFreeze record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_freeze
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PasswordFreeze record);
}