package com.mapper;

import com.mapper.domain.PaymentResultJetpayQrpay;
import com.mapper.domain.PaymentResultJetpayQrpayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentResultJetpayQrpayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    int countByExample(PaymentResultJetpayQrpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    int deleteByExample(PaymentResultJetpayQrpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    int insert(PaymentResultJetpayQrpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    int insertSelective(PaymentResultJetpayQrpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    PaymentResultJetpayQrpay selectOneByExample(PaymentResultJetpayQrpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    List<PaymentResultJetpayQrpay> selectByExample(PaymentResultJetpayQrpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    PaymentResultJetpayQrpay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PaymentResultJetpayQrpay record, @Param("example") PaymentResultJetpayQrpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PaymentResultJetpayQrpay record, @Param("example") PaymentResultJetpayQrpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentResultJetpayQrpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentResultJetpayQrpay record);
}