package com.mapper;

import com.mapper.domain.PaymentResultJetpay;
import com.mapper.domain.PaymentResultJetpayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentResultJetpayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int countByExample(PaymentResultJetpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int deleteByExample(PaymentResultJetpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int insert(PaymentResultJetpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int insertSelective(PaymentResultJetpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    PaymentResultJetpay selectOneByExample(PaymentResultJetpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    List<PaymentResultJetpay> selectByExample(PaymentResultJetpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    PaymentResultJetpay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PaymentResultJetpay record, @Param("example") PaymentResultJetpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PaymentResultJetpay record, @Param("example") PaymentResultJetpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentResultJetpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentResultJetpay record);
}