package com.mapper;

import com.mapper.domain.SendDownWay;
import com.mapper.domain.SendDownWayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SendDownWayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_down_way
     *
     * @mbggenerated
     */
    int countByExample(SendDownWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_down_way
     *
     * @mbggenerated
     */
    int deleteByExample(SendDownWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_down_way
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_down_way
     *
     * @mbggenerated
     */
    int insert(SendDownWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_down_way
     *
     * @mbggenerated
     */
    int insertSelective(SendDownWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_down_way
     *
     * @mbggenerated
     */
    SendDownWay selectOneByExample(SendDownWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_down_way
     *
     * @mbggenerated
     */
    List<SendDownWay> selectByExample(SendDownWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_down_way
     *
     * @mbggenerated
     */
    SendDownWay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_down_way
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SendDownWay record, @Param("example") SendDownWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_down_way
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SendDownWay record, @Param("example") SendDownWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_down_way
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SendDownWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_down_way
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SendDownWay record);
}