package com.mapper;

import com.mapper.domain.TenauspksCountSgds;
import com.mapper.domain.TenauspksCountSgdsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TenauspksCountSgdsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenauspks_count_sgds
     *
     * @mbggenerated
     */
    int countByExample(TenauspksCountSgdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenauspks_count_sgds
     *
     * @mbggenerated
     */
    int deleteByExample(TenauspksCountSgdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenauspks_count_sgds
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenauspks_count_sgds
     *
     * @mbggenerated
     */
    int insert(TenauspksCountSgds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenauspks_count_sgds
     *
     * @mbggenerated
     */
    int insertSelective(TenauspksCountSgds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenauspks_count_sgds
     *
     * @mbggenerated
     */
    TenauspksCountSgds selectOneByExample(TenauspksCountSgdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenauspks_count_sgds
     *
     * @mbggenerated
     */
    List<TenauspksCountSgds> selectByExample(TenauspksCountSgdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenauspks_count_sgds
     *
     * @mbggenerated
     */
    TenauspksCountSgds selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenauspks_count_sgds
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TenauspksCountSgds record, @Param("example") TenauspksCountSgdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenauspks_count_sgds
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TenauspksCountSgds record, @Param("example") TenauspksCountSgdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenauspks_count_sgds
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TenauspksCountSgds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenauspks_count_sgds
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TenauspksCountSgds record);
}