package com.mapper;

import com.mapper.domain.TenluckpksKillNumber;
import com.mapper.domain.TenluckpksKillNumberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TenluckpksKillNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenluckpks_kill_number
     *
     * @mbggenerated
     */
    int countByExample(TenluckpksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenluckpks_kill_number
     *
     * @mbggenerated
     */
    int deleteByExample(TenluckpksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenluckpks_kill_number
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenluckpks_kill_number
     *
     * @mbggenerated
     */
    int insert(TenluckpksKillNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenluckpks_kill_number
     *
     * @mbggenerated
     */
    int insertSelective(TenluckpksKillNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenluckpks_kill_number
     *
     * @mbggenerated
     */
    TenluckpksKillNumber selectOneByExample(TenluckpksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenluckpks_kill_number
     *
     * @mbggenerated
     */
    List<TenluckpksKillNumber> selectByExample(TenluckpksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenluckpks_kill_number
     *
     * @mbggenerated
     */
    TenluckpksKillNumber selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenluckpks_kill_number
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TenluckpksKillNumber record, @Param("example") TenluckpksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenluckpks_kill_number
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TenluckpksKillNumber record, @Param("example") TenluckpksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenluckpks_kill_number
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TenluckpksKillNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenluckpks_kill_number
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TenluckpksKillNumber record);
}