package com.mapper.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CircleGodPushOrderExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    protected Integer limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public CircleGodPushOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        offset = null;
        limit = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public Integer getLimit() {
        return this.limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public CircleGodPushOrderExample bound(Integer offset, Integer limit) {
        this.offset = offset;
        this.limit = limit;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGodIdIsNull() {
            addCriterion("god_id is null");
            return (Criteria) this;
        }

        public Criteria andGodIdIsNotNull() {
            addCriterion("god_id is not null");
            return (Criteria) this;
        }

        public Criteria andGodIdEqualTo(Integer value) {
            addCriterion("god_id =", value, "godId");
            return (Criteria) this;
        }

        public Criteria andGodIdNotEqualTo(Integer value) {
            addCriterion("god_id <>", value, "godId");
            return (Criteria) this;
        }

        public Criteria andGodIdGreaterThan(Integer value) {
            addCriterion("god_id >", value, "godId");
            return (Criteria) this;
        }

        public Criteria andGodIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("god_id >=", value, "godId");
            return (Criteria) this;
        }

        public Criteria andGodIdLessThan(Integer value) {
            addCriterion("god_id <", value, "godId");
            return (Criteria) this;
        }

        public Criteria andGodIdLessThanOrEqualTo(Integer value) {
            addCriterion("god_id <=", value, "godId");
            return (Criteria) this;
        }

        public Criteria andGodIdIn(List<Integer> values) {
            addCriterion("god_id in", values, "godId");
            return (Criteria) this;
        }

        public Criteria andGodIdNotIn(List<Integer> values) {
            addCriterion("god_id not in", values, "godId");
            return (Criteria) this;
        }

        public Criteria andGodIdBetween(Integer value1, Integer value2) {
            addCriterion("god_id between", value1, value2, "godId");
            return (Criteria) this;
        }

        public Criteria andGodIdNotBetween(Integer value1, Integer value2) {
            addCriterion("god_id not between", value1, value2, "godId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(Integer value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(Integer value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(Integer value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(Integer value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(Integer value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<Integer> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<Integer> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(Integer value1, Integer value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(Integer value1, Integer value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("account is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("account is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("account =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("account <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("account >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("account >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("account <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("account <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("account like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("account not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("account in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("account not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("account between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("account not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andOrderBetIdIsNull() {
            addCriterion("order_bet_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderBetIdIsNotNull() {
            addCriterion("order_bet_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderBetIdEqualTo(Integer value) {
            addCriterion("order_bet_id =", value, "orderBetId");
            return (Criteria) this;
        }

        public Criteria andOrderBetIdNotEqualTo(Integer value) {
            addCriterion("order_bet_id <>", value, "orderBetId");
            return (Criteria) this;
        }

        public Criteria andOrderBetIdGreaterThan(Integer value) {
            addCriterion("order_bet_id >", value, "orderBetId");
            return (Criteria) this;
        }

        public Criteria andOrderBetIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_bet_id >=", value, "orderBetId");
            return (Criteria) this;
        }

        public Criteria andOrderBetIdLessThan(Integer value) {
            addCriterion("order_bet_id <", value, "orderBetId");
            return (Criteria) this;
        }

        public Criteria andOrderBetIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_bet_id <=", value, "orderBetId");
            return (Criteria) this;
        }

        public Criteria andOrderBetIdIn(List<Integer> values) {
            addCriterion("order_bet_id in", values, "orderBetId");
            return (Criteria) this;
        }

        public Criteria andOrderBetIdNotIn(List<Integer> values) {
            addCriterion("order_bet_id not in", values, "orderBetId");
            return (Criteria) this;
        }

        public Criteria andOrderBetIdBetween(Integer value1, Integer value2) {
            addCriterion("order_bet_id between", value1, value2, "orderBetId");
            return (Criteria) this;
        }

        public Criteria andOrderBetIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_bet_id not between", value1, value2, "orderBetId");
            return (Criteria) this;
        }

        public Criteria andLotteryIdIsNull() {
            addCriterion("lottery_id is null");
            return (Criteria) this;
        }

        public Criteria andLotteryIdIsNotNull() {
            addCriterion("lottery_id is not null");
            return (Criteria) this;
        }

        public Criteria andLotteryIdEqualTo(Integer value) {
            addCriterion("lottery_id =", value, "lotteryId");
            return (Criteria) this;
        }

        public Criteria andLotteryIdNotEqualTo(Integer value) {
            addCriterion("lottery_id <>", value, "lotteryId");
            return (Criteria) this;
        }

        public Criteria andLotteryIdGreaterThan(Integer value) {
            addCriterion("lottery_id >", value, "lotteryId");
            return (Criteria) this;
        }

        public Criteria andLotteryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("lottery_id >=", value, "lotteryId");
            return (Criteria) this;
        }

        public Criteria andLotteryIdLessThan(Integer value) {
            addCriterion("lottery_id <", value, "lotteryId");
            return (Criteria) this;
        }

        public Criteria andLotteryIdLessThanOrEqualTo(Integer value) {
            addCriterion("lottery_id <=", value, "lotteryId");
            return (Criteria) this;
        }

        public Criteria andLotteryIdIn(List<Integer> values) {
            addCriterion("lottery_id in", values, "lotteryId");
            return (Criteria) this;
        }

        public Criteria andLotteryIdNotIn(List<Integer> values) {
            addCriterion("lottery_id not in", values, "lotteryId");
            return (Criteria) this;
        }

        public Criteria andLotteryIdBetween(Integer value1, Integer value2) {
            addCriterion("lottery_id between", value1, value2, "lotteryId");
            return (Criteria) this;
        }

        public Criteria andLotteryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("lottery_id not between", value1, value2, "lotteryId");
            return (Criteria) this;
        }

        public Criteria andEnsureOddsIsNull() {
            addCriterion("ensure_odds is null");
            return (Criteria) this;
        }

        public Criteria andEnsureOddsIsNotNull() {
            addCriterion("ensure_odds is not null");
            return (Criteria) this;
        }

        public Criteria andEnsureOddsEqualTo(BigDecimal value) {
            addCriterion("ensure_odds =", value, "ensureOdds");
            return (Criteria) this;
        }

        public Criteria andEnsureOddsNotEqualTo(BigDecimal value) {
            addCriterion("ensure_odds <>", value, "ensureOdds");
            return (Criteria) this;
        }

        public Criteria andEnsureOddsGreaterThan(BigDecimal value) {
            addCriterion("ensure_odds >", value, "ensureOdds");
            return (Criteria) this;
        }

        public Criteria andEnsureOddsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ensure_odds >=", value, "ensureOdds");
            return (Criteria) this;
        }

        public Criteria andEnsureOddsLessThan(BigDecimal value) {
            addCriterion("ensure_odds <", value, "ensureOdds");
            return (Criteria) this;
        }

        public Criteria andEnsureOddsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ensure_odds <=", value, "ensureOdds");
            return (Criteria) this;
        }

        public Criteria andEnsureOddsIn(List<BigDecimal> values) {
            addCriterion("ensure_odds in", values, "ensureOdds");
            return (Criteria) this;
        }

        public Criteria andEnsureOddsNotIn(List<BigDecimal> values) {
            addCriterion("ensure_odds not in", values, "ensureOdds");
            return (Criteria) this;
        }

        public Criteria andEnsureOddsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ensure_odds between", value1, value2, "ensureOdds");
            return (Criteria) this;
        }

        public Criteria andEnsureOddsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ensure_odds not between", value1, value2, "ensureOdds");
            return (Criteria) this;
        }

        public Criteria andBonusScaleIsNull() {
            addCriterion("bonus_scale is null");
            return (Criteria) this;
        }

        public Criteria andBonusScaleIsNotNull() {
            addCriterion("bonus_scale is not null");
            return (Criteria) this;
        }

        public Criteria andBonusScaleEqualTo(BigDecimal value) {
            addCriterion("bonus_scale =", value, "bonusScale");
            return (Criteria) this;
        }

        public Criteria andBonusScaleNotEqualTo(BigDecimal value) {
            addCriterion("bonus_scale <>", value, "bonusScale");
            return (Criteria) this;
        }

        public Criteria andBonusScaleGreaterThan(BigDecimal value) {
            addCriterion("bonus_scale >", value, "bonusScale");
            return (Criteria) this;
        }

        public Criteria andBonusScaleGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bonus_scale >=", value, "bonusScale");
            return (Criteria) this;
        }

        public Criteria andBonusScaleLessThan(BigDecimal value) {
            addCriterion("bonus_scale <", value, "bonusScale");
            return (Criteria) this;
        }

        public Criteria andBonusScaleLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bonus_scale <=", value, "bonusScale");
            return (Criteria) this;
        }

        public Criteria andBonusScaleIn(List<BigDecimal> values) {
            addCriterion("bonus_scale in", values, "bonusScale");
            return (Criteria) this;
        }

        public Criteria andBonusScaleNotIn(List<BigDecimal> values) {
            addCriterion("bonus_scale not in", values, "bonusScale");
            return (Criteria) this;
        }

        public Criteria andBonusScaleBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bonus_scale between", value1, value2, "bonusScale");
            return (Criteria) this;
        }

        public Criteria andBonusScaleNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bonus_scale not between", value1, value2, "bonusScale");
            return (Criteria) this;
        }

        public Criteria andSecretStatusIsNull() {
            addCriterion("secret_status is null");
            return (Criteria) this;
        }

        public Criteria andSecretStatusIsNotNull() {
            addCriterion("secret_status is not null");
            return (Criteria) this;
        }

        public Criteria andSecretStatusEqualTo(Integer value) {
            addCriterion("secret_status =", value, "secretStatus");
            return (Criteria) this;
        }

        public Criteria andSecretStatusNotEqualTo(Integer value) {
            addCriterion("secret_status <>", value, "secretStatus");
            return (Criteria) this;
        }

        public Criteria andSecretStatusGreaterThan(Integer value) {
            addCriterion("secret_status >", value, "secretStatus");
            return (Criteria) this;
        }

        public Criteria andSecretStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("secret_status >=", value, "secretStatus");
            return (Criteria) this;
        }

        public Criteria andSecretStatusLessThan(Integer value) {
            addCriterion("secret_status <", value, "secretStatus");
            return (Criteria) this;
        }

        public Criteria andSecretStatusLessThanOrEqualTo(Integer value) {
            addCriterion("secret_status <=", value, "secretStatus");
            return (Criteria) this;
        }

        public Criteria andSecretStatusIn(List<Integer> values) {
            addCriterion("secret_status in", values, "secretStatus");
            return (Criteria) this;
        }

        public Criteria andSecretStatusNotIn(List<Integer> values) {
            addCriterion("secret_status not in", values, "secretStatus");
            return (Criteria) this;
        }

        public Criteria andSecretStatusBetween(Integer value1, Integer value2) {
            addCriterion("secret_status between", value1, value2, "secretStatus");
            return (Criteria) this;
        }

        public Criteria andSecretStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("secret_status not between", value1, value2, "secretStatus");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeIsNull() {
            addCriterion("god_analyze is null");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeIsNotNull() {
            addCriterion("god_analyze is not null");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeEqualTo(String value) {
            addCriterion("god_analyze =", value, "godAnalyze");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeNotEqualTo(String value) {
            addCriterion("god_analyze <>", value, "godAnalyze");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeGreaterThan(String value) {
            addCriterion("god_analyze >", value, "godAnalyze");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeGreaterThanOrEqualTo(String value) {
            addCriterion("god_analyze >=", value, "godAnalyze");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeLessThan(String value) {
            addCriterion("god_analyze <", value, "godAnalyze");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeLessThanOrEqualTo(String value) {
            addCriterion("god_analyze <=", value, "godAnalyze");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeLike(String value) {
            addCriterion("god_analyze like", value, "godAnalyze");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeNotLike(String value) {
            addCriterion("god_analyze not like", value, "godAnalyze");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeIn(List<String> values) {
            addCriterion("god_analyze in", values, "godAnalyze");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeNotIn(List<String> values) {
            addCriterion("god_analyze not in", values, "godAnalyze");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeBetween(String value1, String value2) {
            addCriterion("god_analyze between", value1, value2, "godAnalyze");
            return (Criteria) this;
        }

        public Criteria andGodAnalyzeNotBetween(String value1, String value2) {
            addCriterion("god_analyze not between", value1, value2, "godAnalyze");
            return (Criteria) this;
        }

        public Criteria andFinishStatusIsNull() {
            addCriterion("finish_status is null");
            return (Criteria) this;
        }

        public Criteria andFinishStatusIsNotNull() {
            addCriterion("finish_status is not null");
            return (Criteria) this;
        }

        public Criteria andFinishStatusEqualTo(Integer value) {
            addCriterion("finish_status =", value, "finishStatus");
            return (Criteria) this;
        }

        public Criteria andFinishStatusNotEqualTo(Integer value) {
            addCriterion("finish_status <>", value, "finishStatus");
            return (Criteria) this;
        }

        public Criteria andFinishStatusGreaterThan(Integer value) {
            addCriterion("finish_status >", value, "finishStatus");
            return (Criteria) this;
        }

        public Criteria andFinishStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("finish_status >=", value, "finishStatus");
            return (Criteria) this;
        }

        public Criteria andFinishStatusLessThan(Integer value) {
            addCriterion("finish_status <", value, "finishStatus");
            return (Criteria) this;
        }

        public Criteria andFinishStatusLessThanOrEqualTo(Integer value) {
            addCriterion("finish_status <=", value, "finishStatus");
            return (Criteria) this;
        }

        public Criteria andFinishStatusIn(List<Integer> values) {
            addCriterion("finish_status in", values, "finishStatus");
            return (Criteria) this;
        }

        public Criteria andFinishStatusNotIn(List<Integer> values) {
            addCriterion("finish_status not in", values, "finishStatus");
            return (Criteria) this;
        }

        public Criteria andFinishStatusBetween(Integer value1, Integer value2) {
            addCriterion("finish_status between", value1, value2, "finishStatus");
            return (Criteria) this;
        }

        public Criteria andFinishStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("finish_status not between", value1, value2, "finishStatus");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("sort is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("sort is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("sort =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("sort <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("sort >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("sort >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("sort <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("sort <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Integer> values) {
            addCriterion("sort in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Integer> values) {
            addCriterion("sort not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("sort between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("sort not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table circle_god_push_order
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table circle_god_push_order
     *
     * @mbggenerated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}