package com.mapper.domain;

import java.io.Serializable;

public class DataValueLevel implements Serializable {
    /**
     * 字段: lhc_xs_recommend_comment.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Integer id;

    
    /**
     * 字段: lhc_xs_recommend_comment.max_val<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 最大值
     *
     * @mbggenerated
     */
    private String maxVal;

    /**
     * 字段: lhc_xs_recommend_comment.min_val<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 最小值
     *
     * @mbggenerated
     */
    private String minVal;
    
    /**
     * 字段: lhc_xs_recommend_comment.code<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 编码
     *
     * @mbggenerated
     */
    private String code;
    
    
    /**
     * 字段: data_value_level.name<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 名称
     *
     * @mbggenerated
     */
    private String name;

    /**
     * 字段: lhc_xs_recommend_comment.create_time<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * 字段: lhc_xs_recommend_comment.deleted<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 是否删除
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lhc_xs_recommend_comment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    

    /**
     * web端图片
     */
    private String wphoto;
    
    /**
     * 苹果端图片
     */
    private String iphoto;
    
    /**
     * 安卓端图片
     */
    private String aphoto;
    
    
    
    
	public String getWphoto() {
		return wphoto;
	}

	public void setWphoto(String wphoto) {
		this.wphoto = wphoto;
	}

	public String getIphoto() {
		return iphoto;
	}

	public void setIphoto(String iphoto) {
		this.iphoto = iphoto;
	}

	public String getAphoto() {
		return aphoto;
	}

	public void setAphoto(String aphoto) {
		this.aphoto = aphoto;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public Integer getDeleted() {
		return deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMaxVal() {
		return maxVal;
	}

	public void setMaxVal(String maxVal) {
		this.maxVal = maxVal;
	}

	public String getMinVal() {
		return minVal;
	}

	public void setMinVal(String minVal) {
		this.minVal = minVal;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_xs_recommend_comment
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMaxVal() == null) ? 0 : getMaxVal().hashCode());
        result = prime * result + ((getMinVal() == null) ? 0 : getMinVal().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getWphoto() == null) ? 0 : getWphoto().hashCode());
        result = prime * result + ((getIphoto() == null) ? 0 : getIphoto().hashCode());
        result = prime * result + ((getAphoto() == null) ? 0 : getAphoto().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_xs_recommend_comment
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", maxVal=").append(maxVal);
        sb.append(", minVal=").append(minVal);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", wphoto=").append(wphoto);
        sb.append(", iphoto=").append(iphoto);
        sb.append(", aphoto=").append(aphoto);
        
        sb.append(", createTime=").append(createTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }
}