package com.mapper.domain;

import java.io.Serializable;

public class JstenpksKillNumber implements Serializable {
    /**
     * 字段: jstenpks_kill_number.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 字段: jstenpks_kill_number.issue<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 期号
     *
     * @mbggenerated
     */
    private String issue;

    /**
     * 字段: jstenpks_kill_number.time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 开奖时间
     *
     * @mbggenerated
     */
    private String time;

    /**
     * 字段: jstenpks_kill_number.number<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 开奖号码
     *
     * @mbggenerated
     */
    private String number;

    /**
     * 字段: jstenpks_kill_number.one<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 冠军的杀号
     *
     * @mbggenerated
     */
    private String one;

    /**
     * 字段: jstenpks_kill_number.two<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 亚军的杀号
     *
     * @mbggenerated
     */
    private String two;

    /**
     * 字段: jstenpks_kill_number.there<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第三名的杀号
     *
     * @mbggenerated
     */
    private String there;

    /**
     * 字段: jstenpks_kill_number.four<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第四名的杀号
     *
     * @mbggenerated
     */
    private String four;

    /**
     * 字段: jstenpks_kill_number.five<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第五名的杀号
     *
     * @mbggenerated
     */
    private String five;

    /**
     * 字段: jstenpks_kill_number.six<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第六名的杀号
     *
     * @mbggenerated
     */
    private String six;

    /**
     * 字段: jstenpks_kill_number.seven<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第七名的杀号
     *
     * @mbggenerated
     */
    private String seven;

    /**
     * 字段: jstenpks_kill_number.eight<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第八名的杀号
     *
     * @mbggenerated
     */
    private String eight;

    /**
     * 字段: jstenpks_kill_number.nine<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第九名的杀号
     *
     * @mbggenerated
     */
    private String nine;

    /**
     * 字段: jstenpks_kill_number.ten<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第十名的杀号
     *
     * @mbggenerated
     */
    private String ten;

    /**
     * 字段: jstenpks_kill_number.create_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 添加时间
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jstenpks_kill_number
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return jstenpks_kill_number.id: 
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: jstenpks_kill_number.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return jstenpks_kill_number.issue: 期号
     *
     * @mbggenerated
     */
    public String getIssue() {
        return issue;
    }

    /**
     * 字段: jstenpks_kill_number.issue<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 期号
     *
     * @mbggenerated
     */
    public void setIssue(String issue) {
        this.issue = issue;
    }

    /**
     * @return jstenpks_kill_number.time: 开奖时间
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * 字段: jstenpks_kill_number.time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 开奖时间
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * @return jstenpks_kill_number.number: 开奖号码
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * 字段: jstenpks_kill_number.number<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 开奖号码
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * @return jstenpks_kill_number.one: 冠军的杀号
     *
     * @mbggenerated
     */
    public String getOne() {
        return one;
    }

    /**
     * 字段: jstenpks_kill_number.one<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 冠军的杀号
     *
     * @mbggenerated
     */
    public void setOne(String one) {
        this.one = one;
    }

    /**
     * @return jstenpks_kill_number.two: 亚军的杀号
     *
     * @mbggenerated
     */
    public String getTwo() {
        return two;
    }

    /**
     * 字段: jstenpks_kill_number.two<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 亚军的杀号
     *
     * @mbggenerated
     */
    public void setTwo(String two) {
        this.two = two;
    }

    /**
     * @return jstenpks_kill_number.there: 第三名的杀号
     *
     * @mbggenerated
     */
    public String getThere() {
        return there;
    }

    /**
     * 字段: jstenpks_kill_number.there<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第三名的杀号
     *
     * @mbggenerated
     */
    public void setThere(String there) {
        this.there = there;
    }

    /**
     * @return jstenpks_kill_number.four: 第四名的杀号
     *
     * @mbggenerated
     */
    public String getFour() {
        return four;
    }

    /**
     * 字段: jstenpks_kill_number.four<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第四名的杀号
     *
     * @mbggenerated
     */
    public void setFour(String four) {
        this.four = four;
    }

    /**
     * @return jstenpks_kill_number.five: 第五名的杀号
     *
     * @mbggenerated
     */
    public String getFive() {
        return five;
    }

    /**
     * 字段: jstenpks_kill_number.five<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第五名的杀号
     *
     * @mbggenerated
     */
    public void setFive(String five) {
        this.five = five;
    }

    /**
     * @return jstenpks_kill_number.six: 第六名的杀号
     *
     * @mbggenerated
     */
    public String getSix() {
        return six;
    }

    /**
     * 字段: jstenpks_kill_number.six<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第六名的杀号
     *
     * @mbggenerated
     */
    public void setSix(String six) {
        this.six = six;
    }

    /**
     * @return jstenpks_kill_number.seven: 第七名的杀号
     *
     * @mbggenerated
     */
    public String getSeven() {
        return seven;
    }

    /**
     * 字段: jstenpks_kill_number.seven<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第七名的杀号
     *
     * @mbggenerated
     */
    public void setSeven(String seven) {
        this.seven = seven;
    }

    /**
     * @return jstenpks_kill_number.eight: 第八名的杀号
     *
     * @mbggenerated
     */
    public String getEight() {
        return eight;
    }

    /**
     * 字段: jstenpks_kill_number.eight<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第八名的杀号
     *
     * @mbggenerated
     */
    public void setEight(String eight) {
        this.eight = eight;
    }

    /**
     * @return jstenpks_kill_number.nine: 第九名的杀号
     *
     * @mbggenerated
     */
    public String getNine() {
        return nine;
    }

    /**
     * 字段: jstenpks_kill_number.nine<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第九名的杀号
     *
     * @mbggenerated
     */
    public void setNine(String nine) {
        this.nine = nine;
    }

    /**
     * @return jstenpks_kill_number.ten: 第十名的杀号
     *
     * @mbggenerated
     */
    public String getTen() {
        return ten;
    }

    /**
     * 字段: jstenpks_kill_number.ten<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第十名的杀号
     *
     * @mbggenerated
     */
    public void setTen(String ten) {
        this.ten = ten;
    }

    /**
     * @return jstenpks_kill_number.create_time: 添加时间
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * 字段: jstenpks_kill_number.create_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 添加时间
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jstenpks_kill_number
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JstenpksKillNumber other = (JstenpksKillNumber) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIssue() == null ? other.getIssue() == null : this.getIssue().equals(other.getIssue()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getOne() == null ? other.getOne() == null : this.getOne().equals(other.getOne()))
            && (this.getTwo() == null ? other.getTwo() == null : this.getTwo().equals(other.getTwo()))
            && (this.getThere() == null ? other.getThere() == null : this.getThere().equals(other.getThere()))
            && (this.getFour() == null ? other.getFour() == null : this.getFour().equals(other.getFour()))
            && (this.getFive() == null ? other.getFive() == null : this.getFive().equals(other.getFive()))
            && (this.getSix() == null ? other.getSix() == null : this.getSix().equals(other.getSix()))
            && (this.getSeven() == null ? other.getSeven() == null : this.getSeven().equals(other.getSeven()))
            && (this.getEight() == null ? other.getEight() == null : this.getEight().equals(other.getEight()))
            && (this.getNine() == null ? other.getNine() == null : this.getNine().equals(other.getNine()))
            && (this.getTen() == null ? other.getTen() == null : this.getTen().equals(other.getTen()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jstenpks_kill_number
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIssue() == null) ? 0 : getIssue().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getOne() == null) ? 0 : getOne().hashCode());
        result = prime * result + ((getTwo() == null) ? 0 : getTwo().hashCode());
        result = prime * result + ((getThere() == null) ? 0 : getThere().hashCode());
        result = prime * result + ((getFour() == null) ? 0 : getFour().hashCode());
        result = prime * result + ((getFive() == null) ? 0 : getFive().hashCode());
        result = prime * result + ((getSix() == null) ? 0 : getSix().hashCode());
        result = prime * result + ((getSeven() == null) ? 0 : getSeven().hashCode());
        result = prime * result + ((getEight() == null) ? 0 : getEight().hashCode());
        result = prime * result + ((getNine() == null) ? 0 : getNine().hashCode());
        result = prime * result + ((getTen() == null) ? 0 : getTen().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jstenpks_kill_number
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", issue=").append(issue);
        sb.append(", time=").append(time);
        sb.append(", number=").append(number);
        sb.append(", one=").append(one);
        sb.append(", two=").append(two);
        sb.append(", there=").append(there);
        sb.append(", four=").append(four);
        sb.append(", five=").append(five);
        sb.append(", six=").append(six);
        sb.append(", seven=").append(seven);
        sb.append(", eight=").append(eight);
        sb.append(", nine=").append(nine);
        sb.append(", ten=").append(ten);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}