package com.mapper.domain;

import java.io.Serializable;
import java.util.Date;

public class LhcXsad implements Serializable {

	/**
     * 瀛楁: lhc_xsad.id<br/>
     * 涓婚敭: 鑷姩澧為暱<br/>
     * 蹇呭～: true<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 10<br/>
     * 璇存槑: 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 瀛楁: lhc_xsad.event_title<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 1000<br/>
     * 璇存槑: 娲诲姩鏍囬
     *
     * @mbggenerated
     */
    private String eventTitle;

    /**
     * 瀛楁: lhc_xsad.system<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 10<br/>
     * 璇存槑: 浣嶈繍绠楁爣璁扮郴缁�
     *
     * @mbggenerated
     */
    private Integer system;

    /**
     * 瀛楁: lhc_xsad.ios_photo_url<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 2000<br/>
     * 璇存槑: IOS鍥剧墖鍦板潃
     *
     * @mbggenerated
     */
    private String iosPhotoUrl;

    /**
     * 瀛楁: lhc_xsad.android_photo_url<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 2000<br/>
     * 璇存槑: 瀹夊崜鍥剧墖鍦板潃
     *
     * @mbggenerated
     */
    private String androidPhotoUrl;

    /**
     * 瀛楁: lhc_xsad.web_photo_url<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 255<br/>
     * 璇存槑: 缃戦〉鍥剧墖鍦板潃
     *
     * @mbggenerated
     */
    private String webPhotoUrl;

    /**
     * 瀛楁: lhc_xsad.create_time<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 19<br/>
     * 璇存槑: 鍙戝竷鏃堕棿
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 瀛楁: lhc_xsad.update_time<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 19<br/>
     * 璇存槑: 鏈�鍚庢洿鏂版椂闂�
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 瀛楁: lhc_xsad.create_username<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 255<br/>
     * 璇存槑: 鍒涘缓浜�
     *
     * @mbggenerated
     */
    private String createUsername;

    /**
     * 瀛楁: lhc_xsad.update_username<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 255<br/>
     * 璇存槑: 鏈�鍚庢洿鏂颁汉
     *
     * @mbggenerated
     */
    private String updateUsername;

    /**
     * 瀛楁: lhc_xsad.activity_status<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 10<br/>
     * 璇存槑: 寮�鍚姸鎬� 0锛屽叧闂� 1寮�鍚�
     *
     * @mbggenerated
     */
    private Integer activityStatus;

    /**
     * 瀛楁: lhc_xsad.attribute_1<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 255<br/>
     * 璇存槑: 鎵╁睍瀛楁1
     *
     * @mbggenerated
     */
    private String attribute1;

    /**
     * 瀛楁: lhc_xsad.attribute_2<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 255<br/>
     * 璇存槑: 鎵╁睍瀛楁2
     *
     * @mbggenerated
     */
    private String attribute2;

    /**
     * 瀛楁: lhc_xsad.attribute_3<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 255<br/>
     * 璇存槑: 鎵╁睍瀛楁3
     *
     * @mbggenerated
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lhc_xsad
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return lhc_xsad.id: 
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 瀛楁: lhc_xsad.id<br/>
     * 涓婚敭: 鑷姩澧為暱<br/>
     * 蹇呭～: true<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 10<br/>
     * 璇存槑: 
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return lhc_xsad.event_title: 娲诲姩鏍囬
     *
     * @mbggenerated
     */
    public String getEventTitle() {
        return eventTitle;
    }

    /**
     * 瀛楁: lhc_xsad.event_title<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 1000<br/>
     * 璇存槑: 娲诲姩鏍囬
     *
     * @mbggenerated
     */
    public void setEventTitle(String eventTitle) {
        this.eventTitle = eventTitle;
    }

    /**
     * @return lhc_xsad.system: 浣嶈繍绠楁爣璁扮郴缁�
     *
     * @mbggenerated
     */
    public Integer getSystem() {
        return system;
    }

    /**
     * 瀛楁: lhc_xsad.system<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 10<br/>
     * 璇存槑: 浣嶈繍绠楁爣璁扮郴缁�
     *
     * @mbggenerated
     */
    public void setSystem(Integer system) {
        this.system = system;
    }

    /**
     * @return lhc_xsad.ios_photo_url: IOS鍥剧墖鍦板潃
     *
     * @mbggenerated
     */
    public String getIosPhotoUrl() {
        return iosPhotoUrl;
    }

    /**
     * 瀛楁: lhc_xsad.ios_photo_url<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 2000<br/>
     * 璇存槑: IOS鍥剧墖鍦板潃
     *
     * @mbggenerated
     */
    public void setIosPhotoUrl(String iosPhotoUrl) {
        this.iosPhotoUrl = iosPhotoUrl;
    }

    /**
     * @return lhc_xsad.android_photo_url: 瀹夊崜鍥剧墖鍦板潃
     *
     * @mbggenerated
     */
    public String getAndroidPhotoUrl() {
        return androidPhotoUrl;
    }

    /**
     * 瀛楁: lhc_xsad.android_photo_url<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 2000<br/>
     * 璇存槑: 瀹夊崜鍥剧墖鍦板潃
     *
     * @mbggenerated
     */
    public void setAndroidPhotoUrl(String androidPhotoUrl) {
        this.androidPhotoUrl = androidPhotoUrl;
    }

    /**
     * @return lhc_xsad.web_photo_url: 缃戦〉鍥剧墖鍦板潃
     *
     * @mbggenerated
     */
    public String getWebPhotoUrl() {
        return webPhotoUrl;
    }

    /**
     * 瀛楁: lhc_xsad.web_photo_url<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 255<br/>
     * 璇存槑: 缃戦〉鍥剧墖鍦板潃
     *
     * @mbggenerated
     */
    public void setWebPhotoUrl(String webPhotoUrl) {
        this.webPhotoUrl = webPhotoUrl;
    }

    /**
     * @return lhc_xsad.create_time: 鍙戝竷鏃堕棿
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 瀛楁: lhc_xsad.create_time<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 19<br/>
     * 璇存槑: 鍙戝竷鏃堕棿
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return lhc_xsad.update_time: 鏈�鍚庢洿鏂版椂闂�
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 瀛楁: lhc_xsad.update_time<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 19<br/>
     * 璇存槑: 鏈�鍚庢洿鏂版椂闂�
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * @return lhc_xsad.create_username: 鍒涘缓浜�
     *
     * @mbggenerated
     */
    public String getCreateUsername() {
        return createUsername;
    }

    /**
     * 瀛楁: lhc_xsad.create_username<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 255<br/>
     * 璇存槑: 鍒涘缓浜�
     *
     * @mbggenerated
     */
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername;
    }

    /**
     * @return lhc_xsad.update_username: 鏈�鍚庢洿鏂颁汉
     *
     * @mbggenerated
     */
    public String getUpdateUsername() {
        return updateUsername;
    }

    /**
     * 瀛楁: lhc_xsad.update_username<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 255<br/>
     * 璇存槑: 鏈�鍚庢洿鏂颁汉
     *
     * @mbggenerated
     */
    public void setUpdateUsername(String updateUsername) {
        this.updateUsername = updateUsername;
    }

    /**
     * @return lhc_xsad.activity_status: 寮�鍚姸鎬� 0锛屽叧闂� 1寮�鍚�
     *
     * @mbggenerated
     */
    public Integer getActivityStatus() {
        return activityStatus;
    }

    /**
     * 瀛楁: lhc_xsad.activity_status<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 10<br/>
     * 璇存槑: 寮�鍚姸鎬� 0锛屽叧闂� 1寮�鍚�
     *
     * @mbggenerated
     */
    public void setActivityStatus(Integer activityStatus) {
        this.activityStatus = activityStatus;
    }

    /**
     * @return lhc_xsad.attribute_1: 鎵╁睍瀛楁1
     *
     * @mbggenerated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * 瀛楁: lhc_xsad.attribute_1<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 255<br/>
     * 璇存槑: 鎵╁睍瀛楁1
     *
     * @mbggenerated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * @return lhc_xsad.attribute_2: 鎵╁睍瀛楁2
     *
     * @mbggenerated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * 瀛楁: lhc_xsad.attribute_2<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 255<br/>
     * 璇存槑: 鎵╁睍瀛楁2
     *
     * @mbggenerated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * @return lhc_xsad.attribute_3: 鎵╁睍瀛楁3
     *
     * @mbggenerated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * 瀛楁: lhc_xsad.attribute_3<br/>
     * 蹇呭～: false<br/>
     * 缂虹渷: <br/>
     * 闀垮害: 255<br/>
     * 璇存槑: 鎵╁睍瀛楁3
     *
     * @mbggenerated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_xsad
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LhcXsad other = (LhcXsad) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEventTitle() == null ? other.getEventTitle() == null : this.getEventTitle().equals(other.getEventTitle()))
            && (this.getSystem() == null ? other.getSystem() == null : this.getSystem().equals(other.getSystem()))
            && (this.getIosPhotoUrl() == null ? other.getIosPhotoUrl() == null : this.getIosPhotoUrl().equals(other.getIosPhotoUrl()))
            && (this.getAndroidPhotoUrl() == null ? other.getAndroidPhotoUrl() == null : this.getAndroidPhotoUrl().equals(other.getAndroidPhotoUrl()))
            && (this.getWebPhotoUrl() == null ? other.getWebPhotoUrl() == null : this.getWebPhotoUrl().equals(other.getWebPhotoUrl()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateUsername() == null ? other.getCreateUsername() == null : this.getCreateUsername().equals(other.getCreateUsername()))
            && (this.getUpdateUsername() == null ? other.getUpdateUsername() == null : this.getUpdateUsername().equals(other.getUpdateUsername()))
            && (this.getActivityStatus() == null ? other.getActivityStatus() == null : this.getActivityStatus().equals(other.getActivityStatus()))
            && (this.getAttribute1() == null ? other.getAttribute1() == null : this.getAttribute1().equals(other.getAttribute1()))
            && (this.getAttribute2() == null ? other.getAttribute2() == null : this.getAttribute2().equals(other.getAttribute2()))
            && (this.getAttribute3() == null ? other.getAttribute3() == null : this.getAttribute3().equals(other.getAttribute3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_xsad
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEventTitle() == null) ? 0 : getEventTitle().hashCode());
        result = prime * result + ((getSystem() == null) ? 0 : getSystem().hashCode());
        result = prime * result + ((getIosPhotoUrl() == null) ? 0 : getIosPhotoUrl().hashCode());
        result = prime * result + ((getAndroidPhotoUrl() == null) ? 0 : getAndroidPhotoUrl().hashCode());
        result = prime * result + ((getWebPhotoUrl() == null) ? 0 : getWebPhotoUrl().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateUsername() == null) ? 0 : getCreateUsername().hashCode());
        result = prime * result + ((getUpdateUsername() == null) ? 0 : getUpdateUsername().hashCode());
        result = prime * result + ((getActivityStatus() == null) ? 0 : getActivityStatus().hashCode());
        result = prime * result + ((getAttribute1() == null) ? 0 : getAttribute1().hashCode());
        result = prime * result + ((getAttribute2() == null) ? 0 : getAttribute2().hashCode());
        result = prime * result + ((getAttribute3() == null) ? 0 : getAttribute3().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lhc_xsad
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eventTitle=").append(eventTitle);
        sb.append(", system=").append(system);
        sb.append(", iosPhotoUrl=").append(iosPhotoUrl);
        sb.append(", androidPhotoUrl=").append(androidPhotoUrl);
        sb.append(", webPhotoUrl=").append(webPhotoUrl);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createUsername=").append(createUsername);
        sb.append(", updateUsername=").append(updateUsername);
        sb.append(", activityStatus=").append(activityStatus);
        sb.append(", attribute1=").append(attribute1);
        sb.append(", attribute2=").append(attribute2);
        sb.append(", attribute3=").append(attribute3);
        sb.append("]");
        return sb.toString();
    }
}