package com.mapper.domain;

import java.io.Serializable;

public class MemberRealTimeMessage implements Serializable {
    /**
     * 字段: member_real_time_message.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 字段: member_real_time_message.message<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 通知的内容
     *
     * @mbggenerated
     */
    private String message;

    /**
     * 字段: member_real_time_message.accounts<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 通知的用户
     *
     * @mbggenerated
     */
    private String accounts;

    /**
     * 字段: member_real_time_message.youmeng<br/>
     * 必填: false<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 是否使用友盟:0,不使用;1,使用
     *
     * @mbggenerated
     */
    private Integer youmeng;

    /**
     * 字段: member_real_time_message.operater<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 操作员的账号
     *
     * @mbggenerated
     */
    private String operater;

    /**
     * 字段: member_real_time_message.create_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member_real_time_message
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return member_real_time_message.id: 
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: member_real_time_message.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return member_real_time_message.message: 通知的内容
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * 字段: member_real_time_message.message<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 通知的内容
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * @return member_real_time_message.accounts: 通知的用户
     *
     * @mbggenerated
     */
    public String getAccounts() {
        return accounts;
    }

    /**
     * 字段: member_real_time_message.accounts<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 通知的用户
     *
     * @mbggenerated
     */
    public void setAccounts(String accounts) {
        this.accounts = accounts;
    }

    /**
     * @return member_real_time_message.youmeng: 是否使用友盟:0,不使用;1,使用
     *
     * @mbggenerated
     */
    public Integer getYoumeng() {
        return youmeng;
    }

    /**
     * 字段: member_real_time_message.youmeng<br/>
     * 必填: false<br/>
     * 缺省: 0<br/>
     * 长度: 10<br/>
     * 说明: 是否使用友盟:0,不使用;1,使用
     *
     * @mbggenerated
     */
    public void setYoumeng(Integer youmeng) {
        this.youmeng = youmeng;
    }

    /**
     * @return member_real_time_message.operater: 操作员的账号
     *
     * @mbggenerated
     */
    public String getOperater() {
        return operater;
    }

    /**
     * 字段: member_real_time_message.operater<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 操作员的账号
     *
     * @mbggenerated
     */
    public void setOperater(String operater) {
        this.operater = operater;
    }

    /**
     * @return member_real_time_message.create_time: 创建时间
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * 字段: member_real_time_message.create_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_real_time_message
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MemberRealTimeMessage other = (MemberRealTimeMessage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMessage() == null ? other.getMessage() == null : this.getMessage().equals(other.getMessage()))
            && (this.getAccounts() == null ? other.getAccounts() == null : this.getAccounts().equals(other.getAccounts()))
            && (this.getYoumeng() == null ? other.getYoumeng() == null : this.getYoumeng().equals(other.getYoumeng()))
            && (this.getOperater() == null ? other.getOperater() == null : this.getOperater().equals(other.getOperater()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_real_time_message
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMessage() == null) ? 0 : getMessage().hashCode());
        result = prime * result + ((getAccounts() == null) ? 0 : getAccounts().hashCode());
        result = prime * result + ((getYoumeng() == null) ? 0 : getYoumeng().hashCode());
        result = prime * result + ((getOperater() == null) ? 0 : getOperater().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_real_time_message
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", message=").append(message);
        sb.append(", accounts=").append(accounts);
        sb.append(", youmeng=").append(youmeng);
        sb.append(", operater=").append(operater);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}