package com.mapper.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class PaymentResultJetpayQrpayExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    protected Integer limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public PaymentResultJetpayQrpayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        offset = null;
        limit = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public Integer getLimit() {
        return this.limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public PaymentResultJetpayQrpayExample bound(Integer offset, Integer limit) {
        this.offset = offset;
        this.limit = limit;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMercodeIsNull() {
            addCriterion("merCode is null");
            return (Criteria) this;
        }

        public Criteria andMercodeIsNotNull() {
            addCriterion("merCode is not null");
            return (Criteria) this;
        }

        public Criteria andMercodeEqualTo(String value) {
            addCriterion("merCode =", value, "mercode");
            return (Criteria) this;
        }

        public Criteria andMercodeNotEqualTo(String value) {
            addCriterion("merCode <>", value, "mercode");
            return (Criteria) this;
        }

        public Criteria andMercodeGreaterThan(String value) {
            addCriterion("merCode >", value, "mercode");
            return (Criteria) this;
        }

        public Criteria andMercodeGreaterThanOrEqualTo(String value) {
            addCriterion("merCode >=", value, "mercode");
            return (Criteria) this;
        }

        public Criteria andMercodeLessThan(String value) {
            addCriterion("merCode <", value, "mercode");
            return (Criteria) this;
        }

        public Criteria andMercodeLessThanOrEqualTo(String value) {
            addCriterion("merCode <=", value, "mercode");
            return (Criteria) this;
        }

        public Criteria andMercodeLike(String value) {
            addCriterion("merCode like", value, "mercode");
            return (Criteria) this;
        }

        public Criteria andMercodeNotLike(String value) {
            addCriterion("merCode not like", value, "mercode");
            return (Criteria) this;
        }

        public Criteria andMercodeIn(List<String> values) {
            addCriterion("merCode in", values, "mercode");
            return (Criteria) this;
        }

        public Criteria andMercodeNotIn(List<String> values) {
            addCriterion("merCode not in", values, "mercode");
            return (Criteria) this;
        }

        public Criteria andMercodeBetween(String value1, String value2) {
            addCriterion("merCode between", value1, value2, "mercode");
            return (Criteria) this;
        }

        public Criteria andMercodeNotBetween(String value1, String value2) {
            addCriterion("merCode not between", value1, value2, "mercode");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNull() {
            addCriterion("orderNo is null");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNotNull() {
            addCriterion("orderNo is not null");
            return (Criteria) this;
        }

        public Criteria andOrdernoEqualTo(String value) {
            addCriterion("orderNo =", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotEqualTo(String value) {
            addCriterion("orderNo <>", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThan(String value) {
            addCriterion("orderNo >", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThanOrEqualTo(String value) {
            addCriterion("orderNo >=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThan(String value) {
            addCriterion("orderNo <", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThanOrEqualTo(String value) {
            addCriterion("orderNo <=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLike(String value) {
            addCriterion("orderNo like", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotLike(String value) {
            addCriterion("orderNo not like", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoIn(List<String> values) {
            addCriterion("orderNo in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotIn(List<String> values) {
            addCriterion("orderNo not in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoBetween(String value1, String value2) {
            addCriterion("orderNo between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotBetween(String value1, String value2) {
            addCriterion("orderNo not between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlIsNull() {
            addCriterion("qrCodeUrl is null");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlIsNotNull() {
            addCriterion("qrCodeUrl is not null");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlEqualTo(String value) {
            addCriterion("qrCodeUrl =", value, "qrcodeurl");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlNotEqualTo(String value) {
            addCriterion("qrCodeUrl <>", value, "qrcodeurl");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlGreaterThan(String value) {
            addCriterion("qrCodeUrl >", value, "qrcodeurl");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlGreaterThanOrEqualTo(String value) {
            addCriterion("qrCodeUrl >=", value, "qrcodeurl");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlLessThan(String value) {
            addCriterion("qrCodeUrl <", value, "qrcodeurl");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlLessThanOrEqualTo(String value) {
            addCriterion("qrCodeUrl <=", value, "qrcodeurl");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlLike(String value) {
            addCriterion("qrCodeUrl like", value, "qrcodeurl");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlNotLike(String value) {
            addCriterion("qrCodeUrl not like", value, "qrcodeurl");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlIn(List<String> values) {
            addCriterion("qrCodeUrl in", values, "qrcodeurl");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlNotIn(List<String> values) {
            addCriterion("qrCodeUrl not in", values, "qrcodeurl");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlBetween(String value1, String value2) {
            addCriterion("qrCodeUrl between", value1, value2, "qrcodeurl");
            return (Criteria) this;
        }

        public Criteria andQrcodeurlNotBetween(String value1, String value2) {
            addCriterion("qrCodeUrl not between", value1, value2, "qrcodeurl");
            return (Criteria) this;
        }

        public Criteria andResultcodeIsNull() {
            addCriterion("resultCode is null");
            return (Criteria) this;
        }

        public Criteria andResultcodeIsNotNull() {
            addCriterion("resultCode is not null");
            return (Criteria) this;
        }

        public Criteria andResultcodeEqualTo(String value) {
            addCriterion("resultCode =", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeNotEqualTo(String value) {
            addCriterion("resultCode <>", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeGreaterThan(String value) {
            addCriterion("resultCode >", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeGreaterThanOrEqualTo(String value) {
            addCriterion("resultCode >=", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeLessThan(String value) {
            addCriterion("resultCode <", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeLessThanOrEqualTo(String value) {
            addCriterion("resultCode <=", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeLike(String value) {
            addCriterion("resultCode like", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeNotLike(String value) {
            addCriterion("resultCode not like", value, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeIn(List<String> values) {
            addCriterion("resultCode in", values, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeNotIn(List<String> values) {
            addCriterion("resultCode not in", values, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeBetween(String value1, String value2) {
            addCriterion("resultCode between", value1, value2, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultcodeNotBetween(String value1, String value2) {
            addCriterion("resultCode not between", value1, value2, "resultcode");
            return (Criteria) this;
        }

        public Criteria andResultstatusIsNull() {
            addCriterion("resultStatus is null");
            return (Criteria) this;
        }

        public Criteria andResultstatusIsNotNull() {
            addCriterion("resultStatus is not null");
            return (Criteria) this;
        }

        public Criteria andResultstatusEqualTo(String value) {
            addCriterion("resultStatus =", value, "resultstatus");
            return (Criteria) this;
        }

        public Criteria andResultstatusNotEqualTo(String value) {
            addCriterion("resultStatus <>", value, "resultstatus");
            return (Criteria) this;
        }

        public Criteria andResultstatusGreaterThan(String value) {
            addCriterion("resultStatus >", value, "resultstatus");
            return (Criteria) this;
        }

        public Criteria andResultstatusGreaterThanOrEqualTo(String value) {
            addCriterion("resultStatus >=", value, "resultstatus");
            return (Criteria) this;
        }

        public Criteria andResultstatusLessThan(String value) {
            addCriterion("resultStatus <", value, "resultstatus");
            return (Criteria) this;
        }

        public Criteria andResultstatusLessThanOrEqualTo(String value) {
            addCriterion("resultStatus <=", value, "resultstatus");
            return (Criteria) this;
        }

        public Criteria andResultstatusLike(String value) {
            addCriterion("resultStatus like", value, "resultstatus");
            return (Criteria) this;
        }

        public Criteria andResultstatusNotLike(String value) {
            addCriterion("resultStatus not like", value, "resultstatus");
            return (Criteria) this;
        }

        public Criteria andResultstatusIn(List<String> values) {
            addCriterion("resultStatus in", values, "resultstatus");
            return (Criteria) this;
        }

        public Criteria andResultstatusNotIn(List<String> values) {
            addCriterion("resultStatus not in", values, "resultstatus");
            return (Criteria) this;
        }

        public Criteria andResultstatusBetween(String value1, String value2) {
            addCriterion("resultStatus between", value1, value2, "resultstatus");
            return (Criteria) this;
        }

        public Criteria andResultstatusNotBetween(String value1, String value2) {
            addCriterion("resultStatus not between", value1, value2, "resultstatus");
            return (Criteria) this;
        }

        public Criteria andResulttimeIsNull() {
            addCriterion("resultTime is null");
            return (Criteria) this;
        }

        public Criteria andResulttimeIsNotNull() {
            addCriterion("resultTime is not null");
            return (Criteria) this;
        }

        public Criteria andResulttimeEqualTo(String value) {
            addCriterion("resultTime =", value, "resulttime");
            return (Criteria) this;
        }

        public Criteria andResulttimeNotEqualTo(String value) {
            addCriterion("resultTime <>", value, "resulttime");
            return (Criteria) this;
        }

        public Criteria andResulttimeGreaterThan(String value) {
            addCriterion("resultTime >", value, "resulttime");
            return (Criteria) this;
        }

        public Criteria andResulttimeGreaterThanOrEqualTo(String value) {
            addCriterion("resultTime >=", value, "resulttime");
            return (Criteria) this;
        }

        public Criteria andResulttimeLessThan(String value) {
            addCriterion("resultTime <", value, "resulttime");
            return (Criteria) this;
        }

        public Criteria andResulttimeLessThanOrEqualTo(String value) {
            addCriterion("resultTime <=", value, "resulttime");
            return (Criteria) this;
        }

        public Criteria andResulttimeLike(String value) {
            addCriterion("resultTime like", value, "resulttime");
            return (Criteria) this;
        }

        public Criteria andResulttimeNotLike(String value) {
            addCriterion("resultTime not like", value, "resulttime");
            return (Criteria) this;
        }

        public Criteria andResulttimeIn(List<String> values) {
            addCriterion("resultTime in", values, "resulttime");
            return (Criteria) this;
        }

        public Criteria andResulttimeNotIn(List<String> values) {
            addCriterion("resultTime not in", values, "resulttime");
            return (Criteria) this;
        }

        public Criteria andResulttimeBetween(String value1, String value2) {
            addCriterion("resultTime between", value1, value2, "resulttime");
            return (Criteria) this;
        }

        public Criteria andResulttimeNotBetween(String value1, String value2) {
            addCriterion("resultTime not between", value1, value2, "resulttime");
            return (Criteria) this;
        }

        public Criteria andSignIsNull() {
            addCriterion("sign is null");
            return (Criteria) this;
        }

        public Criteria andSignIsNotNull() {
            addCriterion("sign is not null");
            return (Criteria) this;
        }

        public Criteria andSignEqualTo(String value) {
            addCriterion("sign =", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotEqualTo(String value) {
            addCriterion("sign <>", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThan(String value) {
            addCriterion("sign >", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThanOrEqualTo(String value) {
            addCriterion("sign >=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThan(String value) {
            addCriterion("sign <", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThanOrEqualTo(String value) {
            addCriterion("sign <=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLike(String value) {
            addCriterion("sign like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotLike(String value) {
            addCriterion("sign not like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignIn(List<String> values) {
            addCriterion("sign in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotIn(List<String> values) {
            addCriterion("sign not in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignBetween(String value1, String value2) {
            addCriterion("sign between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotBetween(String value1, String value2) {
            addCriterion("sign not between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andMenberidIsNull() {
            addCriterion("menberid is null");
            return (Criteria) this;
        }

        public Criteria andMenberidIsNotNull() {
            addCriterion("menberid is not null");
            return (Criteria) this;
        }

        public Criteria andMenberidEqualTo(String value) {
            addCriterion("menberid =", value, "menberid");
            return (Criteria) this;
        }

        public Criteria andMenberidNotEqualTo(String value) {
            addCriterion("menberid <>", value, "menberid");
            return (Criteria) this;
        }

        public Criteria andMenberidGreaterThan(String value) {
            addCriterion("menberid >", value, "menberid");
            return (Criteria) this;
        }

        public Criteria andMenberidGreaterThanOrEqualTo(String value) {
            addCriterion("menberid >=", value, "menberid");
            return (Criteria) this;
        }

        public Criteria andMenberidLessThan(String value) {
            addCriterion("menberid <", value, "menberid");
            return (Criteria) this;
        }

        public Criteria andMenberidLessThanOrEqualTo(String value) {
            addCriterion("menberid <=", value, "menberid");
            return (Criteria) this;
        }

        public Criteria andMenberidLike(String value) {
            addCriterion("menberid like", value, "menberid");
            return (Criteria) this;
        }

        public Criteria andMenberidNotLike(String value) {
            addCriterion("menberid not like", value, "menberid");
            return (Criteria) this;
        }

        public Criteria andMenberidIn(List<String> values) {
            addCriterion("menberid in", values, "menberid");
            return (Criteria) this;
        }

        public Criteria andMenberidNotIn(List<String> values) {
            addCriterion("menberid not in", values, "menberid");
            return (Criteria) this;
        }

        public Criteria andMenberidBetween(String value1, String value2) {
            addCriterion("menberid between", value1, value2, "menberid");
            return (Criteria) this;
        }

        public Criteria andMenberidNotBetween(String value1, String value2) {
            addCriterion("menberid not between", value1, value2, "menberid");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("createtime like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("createtime not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}