package com.mapper.domain;

import java.io.Serializable;

public class PaymentResultJetpayQrpay implements Serializable {
    /**
     * 字段: payment_result_jetpay_qrpay.id<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 字段: payment_result_jetpay_qrpay.merCode<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private String mercode;

    /**
     * 字段: payment_result_jetpay_qrpay.orderNo<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 30<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private String orderno;

    /**
     * 字段: payment_result_jetpay_qrpay.qrCodeUrl<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 256<br/>
     * 说明: 下单地址返回的支付地址
     *
     * @mbggenerated
     */
    private String qrcodeurl;

    /**
     * 字段: payment_result_jetpay_qrpay.resultCode<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 8<br/>
     * 说明: 请求结果0000 表示请求成功，9999：表示失败
     *
     * @mbggenerated
     */
    private String resultcode;

    /**
     * 字段: payment_result_jetpay_qrpay.resultStatus<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 8<br/>
     * 说明: 请求状态FAIL 失败，SUCEESS 成功
     *
     * @mbggenerated
     */
    private String resultstatus;

    /**
     * 字段: payment_result_jetpay_qrpay.resultTime<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 12<br/>
     * 说明: yyyyMMddhhmmss 原样返回
     *
     * @mbggenerated
     */
    private String resulttime;

    /**
     * 字段: payment_result_jetpay_qrpay.sign<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * 字段: payment_result_jetpay_qrpay.menberid<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private String menberid;

    /**
     * 字段: payment_result_jetpay_qrpay.status<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 2<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private String status;

    /**
     * 字段: payment_result_jetpay_qrpay.createtime<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 24<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return payment_result_jetpay_qrpay.id: 
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: payment_result_jetpay_qrpay.id<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return payment_result_jetpay_qrpay.merCode: 
     *
     * @mbggenerated
     */
    public String getMercode() {
        return mercode;
    }

    /**
     * 字段: payment_result_jetpay_qrpay.merCode<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setMercode(String mercode) {
        this.mercode = mercode;
    }

    /**
     * @return payment_result_jetpay_qrpay.orderNo: 
     *
     * @mbggenerated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * 字段: payment_result_jetpay_qrpay.orderNo<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 30<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * @return payment_result_jetpay_qrpay.qrCodeUrl: 下单地址返回的支付地址
     *
     * @mbggenerated
     */
    public String getQrcodeurl() {
        return qrcodeurl;
    }

    /**
     * 字段: payment_result_jetpay_qrpay.qrCodeUrl<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 256<br/>
     * 说明: 下单地址返回的支付地址
     *
     * @mbggenerated
     */
    public void setQrcodeurl(String qrcodeurl) {
        this.qrcodeurl = qrcodeurl;
    }

    /**
     * @return payment_result_jetpay_qrpay.resultCode: 请求结果0000 表示请求成功，9999：表示失败
     *
     * @mbggenerated
     */
    public String getResultcode() {
        return resultcode;
    }

    /**
     * 字段: payment_result_jetpay_qrpay.resultCode<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 8<br/>
     * 说明: 请求结果0000 表示请求成功，9999：表示失败
     *
     * @mbggenerated
     */
    public void setResultcode(String resultcode) {
        this.resultcode = resultcode;
    }

    /**
     * @return payment_result_jetpay_qrpay.resultStatus: 请求状态FAIL 失败，SUCEESS 成功
     *
     * @mbggenerated
     */
    public String getResultstatus() {
        return resultstatus;
    }

    /**
     * 字段: payment_result_jetpay_qrpay.resultStatus<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 8<br/>
     * 说明: 请求状态FAIL 失败，SUCEESS 成功
     *
     * @mbggenerated
     */
    public void setResultstatus(String resultstatus) {
        this.resultstatus = resultstatus;
    }

    /**
     * @return payment_result_jetpay_qrpay.resultTime: yyyyMMddhhmmss 原样返回
     *
     * @mbggenerated
     */
    public String getResulttime() {
        return resulttime;
    }

    /**
     * 字段: payment_result_jetpay_qrpay.resultTime<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 12<br/>
     * 说明: yyyyMMddhhmmss 原样返回
     *
     * @mbggenerated
     */
    public void setResulttime(String resulttime) {
        this.resulttime = resulttime;
    }

    /**
     * @return payment_result_jetpay_qrpay.sign: 
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * 字段: payment_result_jetpay_qrpay.sign<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * @return payment_result_jetpay_qrpay.menberid: 
     *
     * @mbggenerated
     */
    public String getMenberid() {
        return menberid;
    }

    /**
     * 字段: payment_result_jetpay_qrpay.menberid<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setMenberid(String menberid) {
        this.menberid = menberid;
    }

    /**
     * @return payment_result_jetpay_qrpay.status: 
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * 字段: payment_result_jetpay_qrpay.status<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 2<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * @return payment_result_jetpay_qrpay.createtime: 
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * 字段: payment_result_jetpay_qrpay.createtime<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 24<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PaymentResultJetpayQrpay other = (PaymentResultJetpayQrpay) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMercode() == null ? other.getMercode() == null : this.getMercode().equals(other.getMercode()))
            && (this.getOrderno() == null ? other.getOrderno() == null : this.getOrderno().equals(other.getOrderno()))
            && (this.getQrcodeurl() == null ? other.getQrcodeurl() == null : this.getQrcodeurl().equals(other.getQrcodeurl()))
            && (this.getResultcode() == null ? other.getResultcode() == null : this.getResultcode().equals(other.getResultcode()))
            && (this.getResultstatus() == null ? other.getResultstatus() == null : this.getResultstatus().equals(other.getResultstatus()))
            && (this.getResulttime() == null ? other.getResulttime() == null : this.getResulttime().equals(other.getResulttime()))
            && (this.getSign() == null ? other.getSign() == null : this.getSign().equals(other.getSign()))
            && (this.getMenberid() == null ? other.getMenberid() == null : this.getMenberid().equals(other.getMenberid()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMercode() == null) ? 0 : getMercode().hashCode());
        result = prime * result + ((getOrderno() == null) ? 0 : getOrderno().hashCode());
        result = prime * result + ((getQrcodeurl() == null) ? 0 : getQrcodeurl().hashCode());
        result = prime * result + ((getResultcode() == null) ? 0 : getResultcode().hashCode());
        result = prime * result + ((getResultstatus() == null) ? 0 : getResultstatus().hashCode());
        result = prime * result + ((getResulttime() == null) ? 0 : getResulttime().hashCode());
        result = prime * result + ((getSign() == null) ? 0 : getSign().hashCode());
        result = prime * result + ((getMenberid() == null) ? 0 : getMenberid().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result_jetpay_qrpay
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mercode=").append(mercode);
        sb.append(", orderno=").append(orderno);
        sb.append(", qrcodeurl=").append(qrcodeurl);
        sb.append(", resultcode=").append(resultcode);
        sb.append(", resultstatus=").append(resultstatus);
        sb.append(", resulttime=").append(resulttime);
        sb.append(", sign=").append(sign);
        sb.append(", menberid=").append(menberid);
        sb.append(", status=").append(status);
        sb.append(", createtime=").append(createtime);
        sb.append("]");
        return sb.toString();
    }
}