package com.mapper.domain;

import java.io.Serializable;

public class RedisSetting implements Serializable {
    /**
     * 字段: redis_setting.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * 字段: redis_setting.redis_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 类型
     *
     * @mbggenerated
     */
    private String redisType;

    /**
     * 字段: redis_setting.redis_key<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 500<br/>
     * 说明: 键
     *
     * @mbggenerated
     */
    private String redisKey;

    /**
     * 字段: redis_setting.redis_filed<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 500<br/>
     * 说明: 字段
     *
     * @mbggenerated
     */
    private String redisFiled;

    /**
     * 字段: redis_setting.redis_value<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 500<br/>
     * 说明: 值
     *
     * @mbggenerated
     */
    private String redisValue;

    /**
     * 字段: redis_setting.redis_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 时间
     *
     * @mbggenerated
     */
    private String redisTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table redis_setting
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return redis_setting.id: 
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * 字段: redis_setting.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return redis_setting.redis_type: 类型
     *
     * @mbggenerated
     */
    public String getRedisType() {
        return redisType;
    }

    /**
     * 字段: redis_setting.redis_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 类型
     *
     * @mbggenerated
     */
    public void setRedisType(String redisType) {
        this.redisType = redisType;
    }

    /**
     * @return redis_setting.redis_key: 键
     *
     * @mbggenerated
     */
    public String getRedisKey() {
        return redisKey;
    }

    /**
     * 字段: redis_setting.redis_key<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 500<br/>
     * 说明: 键
     *
     * @mbggenerated
     */
    public void setRedisKey(String redisKey) {
        this.redisKey = redisKey;
    }

    /**
     * @return redis_setting.redis_filed: 字段
     *
     * @mbggenerated
     */
    public String getRedisFiled() {
        return redisFiled;
    }

    /**
     * 字段: redis_setting.redis_filed<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 500<br/>
     * 说明: 字段
     *
     * @mbggenerated
     */
    public void setRedisFiled(String redisFiled) {
        this.redisFiled = redisFiled;
    }

    /**
     * @return redis_setting.redis_value: 值
     *
     * @mbggenerated
     */
    public String getRedisValue() {
        return redisValue;
    }

    /**
     * 字段: redis_setting.redis_value<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 500<br/>
     * 说明: 值
     *
     * @mbggenerated
     */
    public void setRedisValue(String redisValue) {
        this.redisValue = redisValue;
    }

    /**
     * @return redis_setting.redis_time: 时间
     *
     * @mbggenerated
     */
    public String getRedisTime() {
        return redisTime;
    }

    /**
     * 字段: redis_setting.redis_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 时间
     *
     * @mbggenerated
     */
    public void setRedisTime(String redisTime) {
        this.redisTime = redisTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redis_setting
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RedisSetting other = (RedisSetting) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRedisType() == null ? other.getRedisType() == null : this.getRedisType().equals(other.getRedisType()))
            && (this.getRedisKey() == null ? other.getRedisKey() == null : this.getRedisKey().equals(other.getRedisKey()))
            && (this.getRedisFiled() == null ? other.getRedisFiled() == null : this.getRedisFiled().equals(other.getRedisFiled()))
            && (this.getRedisValue() == null ? other.getRedisValue() == null : this.getRedisValue().equals(other.getRedisValue()))
            && (this.getRedisTime() == null ? other.getRedisTime() == null : this.getRedisTime().equals(other.getRedisTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redis_setting
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRedisType() == null) ? 0 : getRedisType().hashCode());
        result = prime * result + ((getRedisKey() == null) ? 0 : getRedisKey().hashCode());
        result = prime * result + ((getRedisFiled() == null) ? 0 : getRedisFiled().hashCode());
        result = prime * result + ((getRedisValue() == null) ? 0 : getRedisValue().hashCode());
        result = prime * result + ((getRedisTime() == null) ? 0 : getRedisTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redis_setting
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", redisType=").append(redisType);
        sb.append(", redisKey=").append(redisKey);
        sb.append(", redisFiled=").append(redisFiled);
        sb.append(", redisValue=").append(redisValue);
        sb.append(", redisTime=").append(redisTime);
        sb.append("]");
        return sb.toString();
    }
}