package com.mapper.domain;

import java.io.Serializable;

public class SmsCaptcha implements Serializable {
    /**
     * 字段: sms_captcha.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 字段: sms_captcha.phone<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 11<br/>
     * 说明: 手机号码
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * 字段: sms_captcha.captcha<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 6<br/>
     * 说明: 验证码
     *
     * @mbggenerated
     */
    private String captcha;

    /**
     * 字段: sms_captcha.captcha_type<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 验证码类型，1：注册用户，2：忘记密码
     *
     * @mbggenerated
     */
    private Integer captchaType;

    /**
     * 字段: sms_captcha.biz_id<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 发送回执ID
     *
     * @mbggenerated
     */
    private String bizId;

    /**
     * 字段: sms_captcha.create_time<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_captcha
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return sms_captcha.id: 
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: sms_captcha.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return sms_captcha.phone: 手机号码
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 字段: sms_captcha.phone<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 11<br/>
     * 说明: 手机号码
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * @return sms_captcha.captcha: 验证码
     *
     * @mbggenerated
     */
    public String getCaptcha() {
        return captcha;
    }

    /**
     * 字段: sms_captcha.captcha<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 6<br/>
     * 说明: 验证码
     *
     * @mbggenerated
     */
    public void setCaptcha(String captcha) {
        this.captcha = captcha;
    }

    /**
     * @return sms_captcha.captcha_type: 验证码类型，1：注册用户，2：忘记密码
     *
     * @mbggenerated
     */
    public Integer getCaptchaType() {
        return captchaType;
    }

    /**
     * 字段: sms_captcha.captcha_type<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 验证码类型，1：注册用户，2：忘记密码
     *
     * @mbggenerated
     */
    public void setCaptchaType(Integer captchaType) {
        this.captchaType = captchaType;
    }

    /**
     * @return sms_captcha.biz_id: 发送回执ID
     *
     * @mbggenerated
     */
    public String getBizId() {
        return bizId;
    }

    /**
     * 字段: sms_captcha.biz_id<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 发送回执ID
     *
     * @mbggenerated
     */
    public void setBizId(String bizId) {
        this.bizId = bizId;
    }

    /**
     * @return sms_captcha.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * 字段: sms_captcha.create_time<br/>
     * 必填: true<br/>
     * 缺省: 0<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_captcha
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SmsCaptcha other = (SmsCaptcha) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getCaptcha() == null ? other.getCaptcha() == null : this.getCaptcha().equals(other.getCaptcha()))
            && (this.getCaptchaType() == null ? other.getCaptchaType() == null : this.getCaptchaType().equals(other.getCaptchaType()))
            && (this.getBizId() == null ? other.getBizId() == null : this.getBizId().equals(other.getBizId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_captcha
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getCaptcha() == null) ? 0 : getCaptcha().hashCode());
        result = prime * result + ((getCaptchaType() == null) ? 0 : getCaptchaType().hashCode());
        result = prime * result + ((getBizId() == null) ? 0 : getBizId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_captcha
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", phone=").append(phone);
        sb.append(", captcha=").append(captcha);
        sb.append(", captchaType=").append(captchaType);
        sb.append(", bizId=").append(bizId);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}