package com.mapper.domain;

import java.io.Serializable;

public class TaskSgWithBLOBs extends TaskSg implements Serializable {
    /**
     * 字段: task_sg.content<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 16777215<br/>
     * 说明: 内容
     *
     * @mbggenerated
     */
    private String content;

    /**
     * 字段: task_sg.fail_reason<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 16777215<br/>
     * 说明: 失败原因
     *
     * @mbggenerated
     */
    private String failReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_sg
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return task_sg.content: 内容
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * 字段: task_sg.content<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 16777215<br/>
     * 说明: 内容
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * @return task_sg.fail_reason: 失败原因
     *
     * @mbggenerated
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * 字段: task_sg.fail_reason<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 16777215<br/>
     * 说明: 失败原因
     *
     * @mbggenerated
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sg
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TaskSgWithBLOBs other = (TaskSgWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTaskStatus() == null ? other.getTaskStatus() == null : this.getTaskStatus().equals(other.getTaskStatus()))
            && (this.getTaskType() == null ? other.getTaskType() == null : this.getTaskType().equals(other.getTaskType()))
            && (this.getSendCount() == null ? other.getSendCount() == null : this.getSendCount().equals(other.getSendCount()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCaipiaoType() == null ? other.getCaipiaoType() == null : this.getCaipiaoType().equals(other.getCaipiaoType()))
            && (this.getPlayType() == null ? other.getPlayType() == null : this.getPlayType().equals(other.getPlayType()))
            && (this.getDragonNum() == null ? other.getDragonNum() == null : this.getDragonNum().equals(other.getDragonNum()))
            && (this.getDragonName() == null ? other.getDragonName() == null : this.getDragonName().equals(other.getDragonName()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getFailReason() == null ? other.getFailReason() == null : this.getFailReason().equals(other.getFailReason()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sg
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTaskStatus() == null) ? 0 : getTaskStatus().hashCode());
        result = prime * result + ((getTaskType() == null) ? 0 : getTaskType().hashCode());
        result = prime * result + ((getSendCount() == null) ? 0 : getSendCount().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCaipiaoType() == null) ? 0 : getCaipiaoType().hashCode());
        result = prime * result + ((getPlayType() == null) ? 0 : getPlayType().hashCode());
        result = prime * result + ((getDragonNum() == null) ? 0 : getDragonNum().hashCode());
        result = prime * result + ((getDragonName() == null) ? 0 : getDragonName().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getFailReason() == null) ? 0 : getFailReason().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sg
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", content=").append(content);
        sb.append(", failReason=").append(failReason);
        sb.append("]");
        return sb.toString();
    }
}