package com.mapper.domain;

import java.io.Serializable;
import java.util.Date;

public class TaskSg implements Serializable {
    /**
     * 字段: task_sg.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 主键
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 字段: task_sg.task_status<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 任务状态
     *
     * @mbggenerated
     */
    private Integer taskStatus;

    /**
     * 字段: task_sg.task_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 任务类型
     *
     * @mbggenerated
     */
    private Integer taskType;

    /**
     * 字段: task_sg.send_count<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 执行次数
     *
     * @mbggenerated
     */
    private Integer sendCount;

    /**
     * 字段: task_sg.create_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 字段: task_sg.update_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 字段: task_sg.caipiao_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 彩种
     *
     * @mbggenerated
     */
    private String caipiaoType;

    /**
     * 字段: task_sg.play_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 玩法
     *
     * @mbggenerated
     */
    private String playType;

    /**
     * 字段: task_sg.dragon_num<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 长龙数量
     *
     * @mbggenerated
     */
    private Integer dragonNum;

    /**
     * 字段: task_sg.dragon_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 长龙属性
     *
     * @mbggenerated
     */
    private String dragonName;

    /**
     * 字段: task_sg.deleted<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 0:未删除，1:删除
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * 字段: task_sg.content<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 16777215<br/>
     * 说明: 内容
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_sg
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return task_sg.id: 主键
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: task_sg.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 主键
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return task_sg.task_status: 任务状态
     *
     * @mbggenerated
     */
    public Integer getTaskStatus() {
        return taskStatus;
    }

    /**
     * 字段: task_sg.task_status<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 任务状态
     *
     * @mbggenerated
     */
    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * @return task_sg.task_type: 任务类型
     *
     * @mbggenerated
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * 字段: task_sg.task_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 任务类型
     *
     * @mbggenerated
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * @return task_sg.send_count: 执行次数
     *
     * @mbggenerated
     */
    public Integer getSendCount() {
        return sendCount;
    }

    /**
     * 字段: task_sg.send_count<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 执行次数
     *
     * @mbggenerated
     */
    public void setSendCount(Integer sendCount) {
        this.sendCount = sendCount;
    }

    /**
     * @return task_sg.create_time: 创建时间
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: task_sg.create_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return task_sg.update_time: 更新时间
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 字段: task_sg.update_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 更新时间
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * @return task_sg.caipiao_type: 彩种
     *
     * @mbggenerated
     */
    public String getCaipiaoType() {
        return caipiaoType;
    }

    /**
     * 字段: task_sg.caipiao_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 彩种
     *
     * @mbggenerated
     */
    public void setCaipiaoType(String caipiaoType) {
        this.caipiaoType = caipiaoType;
    }

    /**
     * @return task_sg.play_type: 玩法
     *
     * @mbggenerated
     */
    public String getPlayType() {
        return playType;
    }

    /**
     * 字段: task_sg.play_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 玩法
     *
     * @mbggenerated
     */
    public void setPlayType(String playType) {
        this.playType = playType;
    }

    /**
     * @return task_sg.dragon_num: 长龙数量
     *
     * @mbggenerated
     */
    public Integer getDragonNum() {
        return dragonNum;
    }

    /**
     * 字段: task_sg.dragon_num<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 长龙数量
     *
     * @mbggenerated
     */
    public void setDragonNum(Integer dragonNum) {
        this.dragonNum = dragonNum;
    }

    /**
     * @return task_sg.dragon_name: 长龙属性
     *
     * @mbggenerated
     */
    public String getDragonName() {
        return dragonName;
    }

    /**
     * 字段: task_sg.dragon_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 100<br/>
     * 说明: 长龙属性
     *
     * @mbggenerated
     */
    public void setDragonName(String dragonName) {
        this.dragonName = dragonName;
    }

    /**
     * @return task_sg.deleted: 0:未删除，1:删除
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * 字段: task_sg.deleted<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 0:未删除，1:删除
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * @return task_sg.content: 内容
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * 字段: task_sg.content<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 16777215<br/>
     * 说明: 内容
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sg
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TaskSg other = (TaskSg) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTaskStatus() == null ? other.getTaskStatus() == null : this.getTaskStatus().equals(other.getTaskStatus()))
            && (this.getTaskType() == null ? other.getTaskType() == null : this.getTaskType().equals(other.getTaskType()))
            && (this.getSendCount() == null ? other.getSendCount() == null : this.getSendCount().equals(other.getSendCount()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCaipiaoType() == null ? other.getCaipiaoType() == null : this.getCaipiaoType().equals(other.getCaipiaoType()))
            && (this.getPlayType() == null ? other.getPlayType() == null : this.getPlayType().equals(other.getPlayType()))
            && (this.getDragonNum() == null ? other.getDragonNum() == null : this.getDragonNum().equals(other.getDragonNum()))
            && (this.getDragonName() == null ? other.getDragonName() == null : this.getDragonName().equals(other.getDragonName()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sg
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTaskStatus() == null) ? 0 : getTaskStatus().hashCode());
        result = prime * result + ((getTaskType() == null) ? 0 : getTaskType().hashCode());
        result = prime * result + ((getSendCount() == null) ? 0 : getSendCount().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCaipiaoType() == null) ? 0 : getCaipiaoType().hashCode());
        result = prime * result + ((getPlayType() == null) ? 0 : getPlayType().hashCode());
        result = prime * result + ((getDragonNum() == null) ? 0 : getDragonNum().hashCode());
        result = prime * result + ((getDragonName() == null) ? 0 : getDragonName().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sg
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskStatus=").append(taskStatus);
        sb.append(", taskType=").append(taskType);
        sb.append(", sendCount=").append(sendCount);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", caipiaoType=").append(caipiaoType);
        sb.append(", playType=").append(playType);
        sb.append(", dragonNum=").append(dragonNum);
        sb.append(", dragonName=").append(dragonName);
        sb.append(", deleted=").append(deleted);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}