package com.caipiao.live.common.enums;

/**
 * 系统参数的枚举，替代cpt的SystemInfoEnum
 * cpt使用例子：  systemInfoRest.queryByName(SystemInfoEnum.LOTTERY_VERSION_ZIP_URL.name());
 * 现在使用例子： systemInfoRest.queryByName(SysParameterEnum.REGISTER_MEMBER_ODDS.getCode());
 */
public enum SysParameterEnum {

    PLATFORM_NAME("PLATFORM_NAME", "平台标识"),
    SESSION_TIME("SESSION_TIME", "App的token有效期"),
    SMS_SENDWAIT("SMS_SENDWAIT", "短信验证码发送等待时间"),
    SMS_VALIDATE("SMS_VALIDATE", "短信验证码有效期"),
    H5_URL("H5_URL", "分享H5注册页面地址"),
    DOWNLOAD_URL("DOWNLOAD_URL", "APP下载页"),
    OFFLINE_TIME("OFFLINE_TIME", "直播强制下线时间"),
    NOTALK_TIME("NOTALK_TIME", "禁言时间"),
    SHORTMSG_LIMIT("SHORTMSG_LIMIT", "同IP同手机号短信发送限制条数"),
    SRS_KEY("SRS_KEY", "直播服务加密key"),
    ONLINE_MERGER("ONLINE_MERGER", "直播间断上线记录合并时间"),
    VIDEO_GOLDNUM("VIDEO_GOLDNUM", "发表短视讯"),
    ARTICLE_GOLDNUM("ARTICLE_GOLDNUM", "发表贴文"),
    RECOMMEND_USER("RECOMMEND_USER", "推荐用户"),
    H5_APPDOWNLOAD("H5_APPDOWNLOAD", "H5下载页"),
    APPDOWNLOAD_SENTENCE("APPDOWNLOAD_SENTENCE", "分享的文本"),
    SMS_ONOFF("SMS_ONOFF", "短信开关"),
    SMS_REAL_SEND("SMS_REAL_SEND", "短信是否真实调用发送"),
    REQ_FREQUENCY("REQ_FREQUENCY", "直播在线数据刷新频率"),
    SESSION_TIME_BACK("SESSION_TIME_BACK", "后台token有效期"),
    PLATFORM_SCALE("PLATFORM_SCALE", "平台提成比例"),
    RECHARGEMEAL_NUM("RECHARGEMEAL_NUM", "充值套餐个数"),
    FAMILY_INCARNATE_DAY("FAMILY_INCARNATE_DAY", "家族提现日期"),
    ANCHOR_INCAR_WEEKDAY("ANCHOR_INCAR_WEEKDAY", "主播每周几提现"),
    ANCHOR_INCAR_TIME("ANCHOR_INCAR_TIME", "主播提现时间段"),
    OFF_RECHARGE_KEFU("OFF_RECHARGE_KEFU", "线下充值订单客服"),
    H5_SHORT_URL("H5_SHORT_URL", "分享H5注册页面地址"),
    GUANFANG_RECOMCODE("GUANFANG_RECOMCODE", "官方邀请码"),
    LIVE_HOME_KEFU("LIVE_HOME_KEFU", "直播列表得客服微信"),
    TIXIAN_KEFU("TIXIAN_KEFU", "提现客服微信"),
    H5_APPDOWNLOAD_WEB("H5_APPDOWNLOAD_WEB", "给web端用扫描下载APP"),
    WEBSITE_DOWNCODE("WEBSITE_DOWNCODE", "官网二维码下载APP"),

    KYQP_API_URL("KYQP_API_URL", "开元棋牌API接口"),
    KYQP_API_RECORD_URL("KYQP_API_RECORD_URL", "开元棋牌独立拉单接口"),
    KYQP_AGENT("KYQP_AGENT", "开元棋牌Agent"),
    KYQP_DESKEY("KYQP_DESKEY", "开元棋牌Deskey"),
    KYQP_MD5KEY("KYQP_MD5KEY", "开元棋牌Md5key"),
    KYQP_LINECODE("KYQP_LINECODE", "开元棋牌lineCode"),
    KYQP_BACKURL("KYQP_BACKURL", "开元棋牌回调接口"),

    MANAGE_ISIP("MANAGE_ISIP", "BB直播后台是否启用白名单"),
    PAY_RETURNURL("PAY_RETURNURL", "支付成功后跳转页面"),
    PAY_URL("PAY_URL", "请求支付中心路径"),
    BET_RATIO("BET_RATIO", "直播间主播彩票分成比例"),
    GP_LUCKRATE("GP_LUCKRATE", "大牛牛人计划基础胜率"),

    TENLIVE_SECRETID("TENLIVE_SECRETID", "腾讯云直播SecretId"),
    TENLIVE_SECRETKEY("TENLIVE_SECRETKEY", "腾讯云直播SecretKey"),
    TENLIVE_CALLBACKKEY("TENLIVE_CALLBACKKEY", "腾讯云推流回调key"),

    ASTRICT_IP_LOGIN_STATUS("ASTRICT_IP_LOGIN_STATUS", "限制ip登录状态"),
    ASTRICT_IP_GROUP("ASTRICT_IP_GROUP", "限制的ip"),

    HINT_REFRESH_TIME("HINT_REFRESH_TIME", "提示刷新时间"),
    HINT_VOICE_STATUS("HINT_VOICE_STATUS", "提示声音开关"),

    FREEZE_ACCOUNT_STATUS("FREEZE_ACCOUNT_STATUS", "冻结账号"),
    SHENG_XIAO("SHENG_XIAO", "当前年生肖"),
    ODDS_SET("ODDS_SET", "赔率设置"),

    REGISTER_MEMBER_ODDS("REGISTER_MEMBER_ODDS", "注册用户赔率"),
    REGISTER_MEMBER_BACKWATER("REGISTER_MEMBER_BACKWATER", "注册用户返水"),

    DEMO_ACCOUNT_REGISTER_TIMES("DEMO_ACCOUNT_REGISTER_TIMES", "试玩账号注册次数"),
    REVOKE_SECOND("REVOKE_SECOND", "开放撤单多少秒后生效"),

    BIND_BANK_CARD("BIND_BANK_CARD", "充值必须绑卡"),
    BIND_PHONE("BIND_PHONE", "开启手机绑定"),
    BIND_ALIPAY("BIND_ALIPAY", "支付宝绑定显示"),
    BIND_BANK_CARD_AMOUNT("BIND_BANK_CARD_AMOUNT", "每人可绑银行卡张数"),

    WITHDRAWAL_AMOUNT("WITHDRAWAL_AMOUNT", "提现额度设置"),
    MAX_WITHDRAW_DEPOSIT_TIMES("MAX_WITHDRAW_DEPOSIT_TIMES", "每天最大提现次数"),

    GENERAL_WITHDRAW_DEPOSIT_MAX("GENERAL_WITHDRAW_DEPOSIT_MAX", "普通会员单次提现最大额度"),
    GENERAL_WITHDRAW_DEPOSIT_MIN("GENERAL_WITHDRAW_DEPOSIT_MIN", "普通会员单次提现最小额度"),

    TOPUP_WITHDRAW_DEPOSIT_MAX("TOPUP_WITHDRAW_DEPOSIT_MAX", "充值会员单次提现最大额度"),
    TOPUP_WITHDRAW_DEPOSIT_MIN("TOPUP_WITHDRAW_DEPOSIT_MIN", "充值会员单次提现最小额度"),

    NO_TOP_UP_START_TIME("NO_TOP_UP_START_TIME", "不可提现开始时间"),
    NO_TOP_UP_END_TIME("NO_TOP_UP_END_TIME", "不可提现结束时间"),

    WITHDRAW_DEPOSIT_EXPLAIN("WITHDRAW_DEPOSIT_EXPLAIN", "提现说明"),
    IOS_FIRST_REGISTER_GIVE_MONEY("IOS_FIRST_REGISTER_GIVE_MONEY", "每台IOS手机第一次注册赠送金额"),

    ANDROID_FIRST_REGISTER_GIVE_MONEY("ANDROID_FIRST_REGISTER_GIVE_MONEY", "每台ANDROID手机第一次注册赠送金额"),

    BACKWATER_VIP_SCALE("BACKWATER_VIP_SCALE", "VIP返水比例"),
    BACKWATER_PLATFORM_SCALE("BACKWATER_PLATFORM_SCALE", "后台返水比例"),
    BACKWATER_PATTERN("BACKWATER_PATTERN", "返水模式"),
    BACKWATER_WITHDRAW("BACKWATER_WITHDRAW", "返水可提"),

    BE_SHARER_BET_MIN_MONEY("BE_SHARER_BET_MIN_MONEY", "被分享者最低投注金额"),

    SHARER_GIVE_MONEY("SHARER_GIVE_MONEY", "分享者获得赠送金额"),
    SHARER_GIVE_MONEY_WAY("SHARER_GIVE_MONEY_WAY", "分享者获得赠送金额方式"),

    BE_SHARER_IOS_REGISTER_MONEY("BE_SHARER_IOS_REGISTER_MONEY", "被分享者IOS成功注册获得金额"),
    BE_SHARER_ANDROID_REGISTER_MONEY("BE_SHARER_ANDROID_REGISTER_MONEY", "被分享者ANDROID成功注册获得金额"),
    BE_SHARER_GIVE_MONEY_WAY("BE_SHARER_GIVE_MONEY_WAY", "被分享者获得赠送金额方式"),

    SHARE_BACKWATER_QUOTA("SHARE_BACKWATER_QUOTA", "分享返水限额类型"),
    SHARE_BACKWATER_SCALE("SHARE_BACKWATER_SCALE", "分享返水比例(‰)"),

    WEEK_FIRST_TOP_UP_STATUS("WEEK_FIRST_TOP_UP_STATUS", "周周首充活动状态"),
    WEEK_FIRST_TOP_UP_SCALE("WEEK_FIRST_TOP_UP_SCALE", "周周首充活动赠送比例(%)"),
    WEEK_FIRST_TOP_UP_MAX_MONEY("WEEK_FIRST_TOP_UP_MAX_MONEY", "周周首充活动礼金上限"),

    ACTIVITY_FIRST_TOP_UP_STATUS("ACTIVITY_FIRST_TOP_UP_STATUS", "活动首充活动状态"),
    ACTIVITY_FIRST_TOP_UP_SCALE("ACTIVITY_FIRST_TOP_UP_SCALE", "活动首充活动赠送比例(%)"),
    ACTIVITY_FIRST_TOP_UP_MAX_MONEY("ACTIVITY_FIRST_TOP_UP_MAX_MONEY", "活动首充活动礼金上限"),
    ACTIVITY_FIRST_TOP_UP_START_TIME("ACTIVITY_FIRST_TOP_UP_START_TIME", "活动首充活动开启时间"),
    ACTIVITY_FIRST_TOP_UP_END_TIME("ACTIVITY_FIRST_TOP_UP_END_TIME", "活动首充活动结束时间"),
    ACTIVITY_FIRST_TOP_UP_BACK_SCALE("ACTIVITY_FIRST_TOP_UP_BACK_SCALE", "活动首充活动返还比例"),

    SHARE_BACKWATER_SCALE_ONE("SHARE_BACKWATER_SCALE_ONE", "1层分享返水比例(‰)"),
    SHARE_BACKWATER_SCALE_TWO("SHARE_BACKWATER_SCALE_TWO", "2层分享返水比例(‰)"),

    LOTTERY_VERSION_ZIP_URL("LOTTERY_VERSION_ZIP_URL", "150"),
    SYS_FILE_UPLOAD_URL("SYS_FILE_UPLOAD_URL", "后台文件上传路径"),
    SYSTEM_RECHARGE_TIME("SYSTEM_RECHARGE_TIME", "充值预计时间"),
    SYSTEM_WITH_DRAW_TIME("SYSTEM_WITH_DRAW_TIME", "提现预计时间"),
    SYS_FILE_DOWNLOAD_URL("SYS_FILE_DOWNLOAD_URL", "1"),

    LHTK_MANUAL_MANAGEMENT_NAMES("LHTK_MANUAL_MANAGEMENT_NAMES", "六合图库手动管理图片名"),
    IP_ENROLL("IP_ENROLL", "同IP注册限制"),

    USER_CAPTCHA_ONE_DAY_COUNT("USER_CAPTCHA_ONE_DAY_COUNT", "用户每天能获取的验证码次数"),
    USER_CAPTCHA_FREEZE_HOURS("USER_CAPTCHA_FREEZE_HOURS", "用户验证码禁用时长。单位：小时"),

    CHAT_ROOM_CONTENT("CHAT_ROOM_CONTENT", "聊天室全员禁言"),
    CHAT_ROOM("CHAT_ROOM", "聊天室启停"),
    CHAT_ROOM_PACK("CHAT_ROOM_PACK", "聊天室红包启停"),
    CHAT_PACK_NUMBER("CHAT_PACK_NUMBER", "聊天室个数"),
    CHAT_PACK_AMOUT("CHAT_PACK_AMOUT", "聊天室红包金额"),

    REGISTER_ACCOUNT_CAN_RECOMMEND("REGISTER_ACCOUNT_CAN_RECOMMEND", "注册型用户是否可评论,1:可评论;0:不能评论"),
    REWARD_SET_STATUS("REWARD_SET_STATUS", "打赏开关"),
    AUDIT_SET_STATUS("AUDIT_SET_STATUS", "审核开关"),
    CRATE_AGENT_DATA_SWITCH("CRATE_AGENT_DATA_SWITCH", "项目启动时是否要迁移代理数据"),
    KILL_PLATFORM("KILL_PLATFORM", "设置杀号的所有平台信息"),
    VEST_BAG_SWITCH("VEST_BAG_SWITCH", "0:马甲包开启,1:马甲包关闭"),
    PRE_AEARD("PRE_AEARD", "设置预开奖信息"),
    GOD_PLAN_LOW_LOTTERY("GOD_PLAN_LOW_LOTTERY", "大神计划低频彩"),
    PROXY_WORK_STATUS("PROXY_WORK_STATUS", "1"),
    WEB_FIRST_REGISTER_GIVE_MONEY("WEB_FIRST_REGISTER_GIVE_MONEY", "每台WEB第一次注册赠送金额"),
    H5_FIRST_REGISTER_GIVE_MONEY("H5_FIRST_REGISTER_GIVE_MONEY", "每台H5第一次注册赠送金额"),

    LIVE_USER_ACCOUNT_SENSITIVE_CASE("LIVE_USER_ACCOUNT_SENSITIVE_CASE", "LIVE_USER_ACCOUNT_SENSITIVE_CASE"),
    LIVE_REGISTER_ACCOUNT_CAN_RECOMMEND("LIVE_REGISTER_ACCOUNT_CAN_RECOMMEND", "LIVE_REGISTER_ACCOUNT_CAN_RECOMMEND"),

    LIVE_INVITE_CODE("LIVE_INVITE_CODE", "直播间邀请码"),
    OFFICE_INVITE_CODE("OFFICE_INVITE_CODE", "官方邀请码"),
    SWIPE_VERIFICATION_SWIFT("SWIPE_VERIFICATION_SWIFT", "第三方网易验证码"),
    KEFU_QQ_LINK_NUMBER("KEFU_QQ_LINK_NUMBER", "客服"),

    LIVE_VIDEO_ENCODE("LIVE_VIDEO_ENCODE", "直播视频编码"),
    LIVE_VIDEO_PUSH_ENABLE_H265("LIVE_VIDEO_PUSH_ENABLE_H265", "直播推流视频编码是否启用h265方式"),
    TRANSFORM_TPL_360("TRANSFORM_TPL_360", "360P转码模板"),
    TRANSFORM_TPL_480("TRANSFORM_TPL_480", "480P转码模板"),
    TRANSFORM_TPL_720("TRANSFORM_TPL_720", "720P转码模板"),
    ROOMTALK_LEVEL("ROOMTALK_LEVEL", "直播间发言等级"),
    LIVE_WS_URL("LIVE_WS_URL", "直播ws服务地址"),
    UNIQUE_CODE_GEN_SIZE("UNIQUE_CODE_GEN_SIZE", "生成随机码的个数"),
    UNIQUE_CODE_LOAD_SIZE("UNIQUE_CODE_LOAD_SIZE", "每次加载随机码的个数"),
    LIVE_SG_PUSH_ADDRESS_URL("LIVE_SG_PUSH_ADDRESS_URL", "BB直播赛果推送地址"),
    UNIQUE_CODE_BATCH_SIZE("UNIQUE_CODE_BATCH_SIZE", "每次批量操作随机码的个数"),
    AUDIO_ORDER_RECHARNGE_NOTICE("AUDIO_ORDER_RECHARNGE_NOTICE", "入款订单提示音，请使用有效的音频文件地址"),
    AUDIO_ORDER_WITHDRAWAL_NOTICE("AUDIO_ORDER_WITHDRAWAL_NOTICE", "出款订单提示音，请使用有效的音频文件地址"),
    QUARY_ORDER_frequency("UNIQUE_CODE_BATCH_SIZE", "单位秒，建议不小于30，频繁自动查询可能降低后台性能"),

    SIGN_CHECK_SWITCH("SIGN_CHECK_SWITCH","验签开关，0关1开"),
    SIGN_CHECK_PASS("SIGN_CHECK_PASS","万能签名值"),
    SIGN_CHECK_EXPIRED("SIGN_CHECK_EXPIRED","验签失效时长，单位秒")
    ;


    /**
     * 系统参数的代码
     */
    private String code;

    /**
     * 方便coder理解code的意思，无其它意义
     */
    private String remark;

    SysParameterEnum(String code, String remark) {
        this.code = code;
        this.remark = remark;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}
