package com.caipiao.live.common.mybatis.entity;

import java.io.Serializable;

public class DbGame implements Serializable {
    /**
     * 字段: db_game.id<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * 字段: db_game.m_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 游戏mtype
     *
     * @mbggenerated
     */
    private Integer mType;

    /**
     * 字段: db_game.game_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 游戏名称
     *
     * @mbggenerated
     */
    private String gameName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_game
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return db_game.id: 
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * 字段: db_game.id<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return db_game.m_type: 游戏mtype
     *
     * @mbggenerated
     */
    public Integer getmType() {
        return mType;
    }

    /**
     * 字段: db_game.m_type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 游戏mtype
     *
     * @mbggenerated
     */
    public void setmType(Integer mType) {
        this.mType = mType;
    }

    /**
     * @return db_game.game_name: 游戏名称
     *
     * @mbggenerated
     */
    public String getGameName() {
        return gameName;
    }

    /**
     * 字段: db_game.game_name<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 32<br/>
     * 说明: 游戏名称
     *
     * @mbggenerated
     */
    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_game
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DbGame other = (DbGame) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getmType() == null ? other.getmType() == null : this.getmType().equals(other.getmType()))
            && (this.getGameName() == null ? other.getGameName() == null : this.getGameName().equals(other.getGameName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_game
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getmType() == null) ? 0 : getmType().hashCode());
        result = prime * result + ((getGameName() == null) ? 0 : getGameName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_game
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mType=").append(mType);
        sb.append(", gameName=").append(gameName);
        sb.append("]");
        return sb.toString();
    }
}
