package com.caipiao.live.common.mybatis.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LotteryPlaySettingExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    protected Integer limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public LotteryPlaySettingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        offset = null;
        limit = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public Integer getLimit() {
        return this.limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public LotteryPlaySettingExample bound(Integer offset, Integer limit) {
        this.offset = offset;
        this.limit = limit;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCateIdIsNull() {
            addCriterion("cate_id is null");
            return (Criteria) this;
        }

        public Criteria andCateIdIsNotNull() {
            addCriterion("cate_id is not null");
            return (Criteria) this;
        }

        public Criteria andCateIdEqualTo(Integer value) {
            addCriterion("cate_id =", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdNotEqualTo(Integer value) {
            addCriterion("cate_id <>", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdGreaterThan(Integer value) {
            addCriterion("cate_id >", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cate_id >=", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdLessThan(Integer value) {
            addCriterion("cate_id <", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdLessThanOrEqualTo(Integer value) {
            addCriterion("cate_id <=", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdIn(List<Integer> values) {
            addCriterion("cate_id in", values, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdNotIn(List<Integer> values) {
            addCriterion("cate_id not in", values, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdBetween(Integer value1, Integer value2) {
            addCriterion("cate_id between", value1, value2, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cate_id not between", value1, value2, "cateId");
            return (Criteria) this;
        }

        public Criteria andPlayIdIsNull() {
            addCriterion("play_id is null");
            return (Criteria) this;
        }

        public Criteria andPlayIdIsNotNull() {
            addCriterion("play_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlayIdEqualTo(Integer value) {
            addCriterion("play_id =", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdNotEqualTo(Integer value) {
            addCriterion("play_id <>", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdGreaterThan(Integer value) {
            addCriterion("play_id >", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("play_id >=", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdLessThan(Integer value) {
            addCriterion("play_id <", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdLessThanOrEqualTo(Integer value) {
            addCriterion("play_id <=", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdIn(List<Integer> values) {
            addCriterion("play_id in", values, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdNotIn(List<Integer> values) {
            addCriterion("play_id not in", values, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdBetween(Integer value1, Integer value2) {
            addCriterion("play_id between", value1, value2, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdNotBetween(Integer value1, Integer value2) {
            addCriterion("play_id not between", value1, value2, "playId");
            return (Criteria) this;
        }

        public Criteria andTotalCountIsNull() {
            addCriterion("total_count is null");
            return (Criteria) this;
        }

        public Criteria andTotalCountIsNotNull() {
            addCriterion("total_count is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCountEqualTo(Integer value) {
            addCriterion("total_count =", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotEqualTo(Integer value) {
            addCriterion("total_count <>", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountGreaterThan(Integer value) {
            addCriterion("total_count >", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_count >=", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountLessThan(Integer value) {
            addCriterion("total_count <", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountLessThanOrEqualTo(Integer value) {
            addCriterion("total_count <=", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountIn(List<Integer> values) {
            addCriterion("total_count in", values, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotIn(List<Integer> values) {
            addCriterion("total_count not in", values, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountBetween(Integer value1, Integer value2) {
            addCriterion("total_count between", value1, value2, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotBetween(Integer value1, Integer value2) {
            addCriterion("total_count not between", value1, value2, "totalCount");
            return (Criteria) this;
        }

        public Criteria andWinCountIsNull() {
            addCriterion("win_count is null");
            return (Criteria) this;
        }

        public Criteria andWinCountIsNotNull() {
            addCriterion("win_count is not null");
            return (Criteria) this;
        }

        public Criteria andWinCountEqualTo(Integer value) {
            addCriterion("win_count =", value, "winCount");
            return (Criteria) this;
        }

        public Criteria andWinCountNotEqualTo(Integer value) {
            addCriterion("win_count <>", value, "winCount");
            return (Criteria) this;
        }

        public Criteria andWinCountGreaterThan(Integer value) {
            addCriterion("win_count >", value, "winCount");
            return (Criteria) this;
        }

        public Criteria andWinCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("win_count >=", value, "winCount");
            return (Criteria) this;
        }

        public Criteria andWinCountLessThan(Integer value) {
            addCriterion("win_count <", value, "winCount");
            return (Criteria) this;
        }

        public Criteria andWinCountLessThanOrEqualTo(Integer value) {
            addCriterion("win_count <=", value, "winCount");
            return (Criteria) this;
        }

        public Criteria andWinCountIn(List<Integer> values) {
            addCriterion("win_count in", values, "winCount");
            return (Criteria) this;
        }

        public Criteria andWinCountNotIn(List<Integer> values) {
            addCriterion("win_count not in", values, "winCount");
            return (Criteria) this;
        }

        public Criteria andWinCountBetween(Integer value1, Integer value2) {
            addCriterion("win_count between", value1, value2, "winCount");
            return (Criteria) this;
        }

        public Criteria andWinCountNotBetween(Integer value1, Integer value2) {
            addCriterion("win_count not between", value1, value2, "winCount");
            return (Criteria) this;
        }

        public Criteria andSingleMoneyIsNull() {
            addCriterion("single_money is null");
            return (Criteria) this;
        }

        public Criteria andSingleMoneyIsNotNull() {
            addCriterion("single_money is not null");
            return (Criteria) this;
        }

        public Criteria andSingleMoneyEqualTo(Double value) {
            addCriterion("single_money =", value, "singleMoney");
            return (Criteria) this;
        }

        public Criteria andSingleMoneyNotEqualTo(Double value) {
            addCriterion("single_money <>", value, "singleMoney");
            return (Criteria) this;
        }

        public Criteria andSingleMoneyGreaterThan(Double value) {
            addCriterion("single_money >", value, "singleMoney");
            return (Criteria) this;
        }

        public Criteria andSingleMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("single_money >=", value, "singleMoney");
            return (Criteria) this;
        }

        public Criteria andSingleMoneyLessThan(Double value) {
            addCriterion("single_money <", value, "singleMoney");
            return (Criteria) this;
        }

        public Criteria andSingleMoneyLessThanOrEqualTo(Double value) {
            addCriterion("single_money <=", value, "singleMoney");
            return (Criteria) this;
        }

        public Criteria andSingleMoneyIn(List<Double> values) {
            addCriterion("single_money in", values, "singleMoney");
            return (Criteria) this;
        }

        public Criteria andSingleMoneyNotIn(List<Double> values) {
            addCriterion("single_money not in", values, "singleMoney");
            return (Criteria) this;
        }

        public Criteria andSingleMoneyBetween(Double value1, Double value2) {
            addCriterion("single_money between", value1, value2, "singleMoney");
            return (Criteria) this;
        }

        public Criteria andSingleMoneyNotBetween(Double value1, Double value2) {
            addCriterion("single_money not between", value1, value2, "singleMoney");
            return (Criteria) this;
        }

        public Criteria andExampleIsNull() {
            addCriterion("example is null");
            return (Criteria) this;
        }

        public Criteria andExampleIsNotNull() {
            addCriterion("example is not null");
            return (Criteria) this;
        }

        public Criteria andExampleEqualTo(String value) {
            addCriterion("example =", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleNotEqualTo(String value) {
            addCriterion("example <>", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleGreaterThan(String value) {
            addCriterion("example >", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleGreaterThanOrEqualTo(String value) {
            addCriterion("example >=", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleLessThan(String value) {
            addCriterion("example <", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleLessThanOrEqualTo(String value) {
            addCriterion("example <=", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleLike(String value) {
            addCriterion("example like", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleNotLike(String value) {
            addCriterion("example not like", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleIn(List<String> values) {
            addCriterion("example in", values, "example");
            return (Criteria) this;
        }

        public Criteria andExampleNotIn(List<String> values) {
            addCriterion("example not in", values, "example");
            return (Criteria) this;
        }

        public Criteria andExampleBetween(String value1, String value2) {
            addCriterion("example between", value1, value2, "example");
            return (Criteria) this;
        }

        public Criteria andExampleNotBetween(String value1, String value2) {
            addCriterion("example not between", value1, value2, "example");
            return (Criteria) this;
        }

        public Criteria andExampleNumIsNull() {
            addCriterion("example_num is null");
            return (Criteria) this;
        }

        public Criteria andExampleNumIsNotNull() {
            addCriterion("example_num is not null");
            return (Criteria) this;
        }

        public Criteria andExampleNumEqualTo(String value) {
            addCriterion("example_num =", value, "exampleNum");
            return (Criteria) this;
        }

        public Criteria andExampleNumNotEqualTo(String value) {
            addCriterion("example_num <>", value, "exampleNum");
            return (Criteria) this;
        }

        public Criteria andExampleNumGreaterThan(String value) {
            addCriterion("example_num >", value, "exampleNum");
            return (Criteria) this;
        }

        public Criteria andExampleNumGreaterThanOrEqualTo(String value) {
            addCriterion("example_num >=", value, "exampleNum");
            return (Criteria) this;
        }

        public Criteria andExampleNumLessThan(String value) {
            addCriterion("example_num <", value, "exampleNum");
            return (Criteria) this;
        }

        public Criteria andExampleNumLessThanOrEqualTo(String value) {
            addCriterion("example_num <=", value, "exampleNum");
            return (Criteria) this;
        }

        public Criteria andExampleNumLike(String value) {
            addCriterion("example_num like", value, "exampleNum");
            return (Criteria) this;
        }

        public Criteria andExampleNumNotLike(String value) {
            addCriterion("example_num not like", value, "exampleNum");
            return (Criteria) this;
        }

        public Criteria andExampleNumIn(List<String> values) {
            addCriterion("example_num in", values, "exampleNum");
            return (Criteria) this;
        }

        public Criteria andExampleNumNotIn(List<String> values) {
            addCriterion("example_num not in", values, "exampleNum");
            return (Criteria) this;
        }

        public Criteria andExampleNumBetween(String value1, String value2) {
            addCriterion("example_num between", value1, value2, "exampleNum");
            return (Criteria) this;
        }

        public Criteria andExampleNumNotBetween(String value1, String value2) {
            addCriterion("example_num not between", value1, value2, "exampleNum");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkIsNull() {
            addCriterion("play_remark is null");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkIsNotNull() {
            addCriterion("play_remark is not null");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkEqualTo(String value) {
            addCriterion("play_remark =", value, "playRemark");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkNotEqualTo(String value) {
            addCriterion("play_remark <>", value, "playRemark");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkGreaterThan(String value) {
            addCriterion("play_remark >", value, "playRemark");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("play_remark >=", value, "playRemark");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkLessThan(String value) {
            addCriterion("play_remark <", value, "playRemark");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkLessThanOrEqualTo(String value) {
            addCriterion("play_remark <=", value, "playRemark");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkLike(String value) {
            addCriterion("play_remark like", value, "playRemark");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkNotLike(String value) {
            addCriterion("play_remark not like", value, "playRemark");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkIn(List<String> values) {
            addCriterion("play_remark in", values, "playRemark");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkNotIn(List<String> values) {
            addCriterion("play_remark not in", values, "playRemark");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkBetween(String value1, String value2) {
            addCriterion("play_remark between", value1, value2, "playRemark");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkNotBetween(String value1, String value2) {
            addCriterion("play_remark not between", value1, value2, "playRemark");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxIsNull() {
            addCriterion("play_remark_sx is null");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxIsNotNull() {
            addCriterion("play_remark_sx is not null");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxEqualTo(String value) {
            addCriterion("play_remark_sx =", value, "playRemarkSx");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxNotEqualTo(String value) {
            addCriterion("play_remark_sx <>", value, "playRemarkSx");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxGreaterThan(String value) {
            addCriterion("play_remark_sx >", value, "playRemarkSx");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxGreaterThanOrEqualTo(String value) {
            addCriterion("play_remark_sx >=", value, "playRemarkSx");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxLessThan(String value) {
            addCriterion("play_remark_sx <", value, "playRemarkSx");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxLessThanOrEqualTo(String value) {
            addCriterion("play_remark_sx <=", value, "playRemarkSx");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxLike(String value) {
            addCriterion("play_remark_sx like", value, "playRemarkSx");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxNotLike(String value) {
            addCriterion("play_remark_sx not like", value, "playRemarkSx");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxIn(List<String> values) {
            addCriterion("play_remark_sx in", values, "playRemarkSx");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxNotIn(List<String> values) {
            addCriterion("play_remark_sx not in", values, "playRemarkSx");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxBetween(String value1, String value2) {
            addCriterion("play_remark_sx between", value1, value2, "playRemarkSx");
            return (Criteria) this;
        }

        public Criteria andPlayRemarkSxNotBetween(String value1, String value2) {
            addCriterion("play_remark_sx not between", value1, value2, "playRemarkSx");
            return (Criteria) this;
        }

        public Criteria andRewardIsNull() {
            addCriterion("reward is null");
            return (Criteria) this;
        }

        public Criteria andRewardIsNotNull() {
            addCriterion("reward is not null");
            return (Criteria) this;
        }

        public Criteria andRewardEqualTo(String value) {
            addCriterion("reward =", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotEqualTo(String value) {
            addCriterion("reward <>", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardGreaterThan(String value) {
            addCriterion("reward >", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardGreaterThanOrEqualTo(String value) {
            addCriterion("reward >=", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardLessThan(String value) {
            addCriterion("reward <", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardLessThanOrEqualTo(String value) {
            addCriterion("reward <=", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardLike(String value) {
            addCriterion("reward like", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotLike(String value) {
            addCriterion("reward not like", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardIn(List<String> values) {
            addCriterion("reward in", values, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotIn(List<String> values) {
            addCriterion("reward not in", values, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardBetween(String value1, String value2) {
            addCriterion("reward between", value1, value2, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotBetween(String value1, String value2) {
            addCriterion("reward not between", value1, value2, "reward");
            return (Criteria) this;
        }

        public Criteria andMatchtypeIsNull() {
            addCriterion("matchtype is null");
            return (Criteria) this;
        }

        public Criteria andMatchtypeIsNotNull() {
            addCriterion("matchtype is not null");
            return (Criteria) this;
        }

        public Criteria andMatchtypeEqualTo(String value) {
            addCriterion("matchtype =", value, "matchtype");
            return (Criteria) this;
        }

        public Criteria andMatchtypeNotEqualTo(String value) {
            addCriterion("matchtype <>", value, "matchtype");
            return (Criteria) this;
        }

        public Criteria andMatchtypeGreaterThan(String value) {
            addCriterion("matchtype >", value, "matchtype");
            return (Criteria) this;
        }

        public Criteria andMatchtypeGreaterThanOrEqualTo(String value) {
            addCriterion("matchtype >=", value, "matchtype");
            return (Criteria) this;
        }

        public Criteria andMatchtypeLessThan(String value) {
            addCriterion("matchtype <", value, "matchtype");
            return (Criteria) this;
        }

        public Criteria andMatchtypeLessThanOrEqualTo(String value) {
            addCriterion("matchtype <=", value, "matchtype");
            return (Criteria) this;
        }

        public Criteria andMatchtypeLike(String value) {
            addCriterion("matchtype like", value, "matchtype");
            return (Criteria) this;
        }

        public Criteria andMatchtypeNotLike(String value) {
            addCriterion("matchtype not like", value, "matchtype");
            return (Criteria) this;
        }

        public Criteria andMatchtypeIn(List<String> values) {
            addCriterion("matchtype in", values, "matchtype");
            return (Criteria) this;
        }

        public Criteria andMatchtypeNotIn(List<String> values) {
            addCriterion("matchtype not in", values, "matchtype");
            return (Criteria) this;
        }

        public Criteria andMatchtypeBetween(String value1, String value2) {
            addCriterion("matchtype between", value1, value2, "matchtype");
            return (Criteria) this;
        }

        public Criteria andMatchtypeNotBetween(String value1, String value2) {
            addCriterion("matchtype not between", value1, value2, "matchtype");
            return (Criteria) this;
        }

        public Criteria andWinCountBakIsNull() {
            addCriterion("win_count_bak is null");
            return (Criteria) this;
        }

        public Criteria andWinCountBakIsNotNull() {
            addCriterion("win_count_bak is not null");
            return (Criteria) this;
        }

        public Criteria andWinCountBakEqualTo(Integer value) {
            addCriterion("win_count_bak =", value, "winCountBak");
            return (Criteria) this;
        }

        public Criteria andWinCountBakNotEqualTo(Integer value) {
            addCriterion("win_count_bak <>", value, "winCountBak");
            return (Criteria) this;
        }

        public Criteria andWinCountBakGreaterThan(Integer value) {
            addCriterion("win_count_bak >", value, "winCountBak");
            return (Criteria) this;
        }

        public Criteria andWinCountBakGreaterThanOrEqualTo(Integer value) {
            addCriterion("win_count_bak >=", value, "winCountBak");
            return (Criteria) this;
        }

        public Criteria andWinCountBakLessThan(Integer value) {
            addCriterion("win_count_bak <", value, "winCountBak");
            return (Criteria) this;
        }

        public Criteria andWinCountBakLessThanOrEqualTo(Integer value) {
            addCriterion("win_count_bak <=", value, "winCountBak");
            return (Criteria) this;
        }

        public Criteria andWinCountBakIn(List<Integer> values) {
            addCriterion("win_count_bak in", values, "winCountBak");
            return (Criteria) this;
        }

        public Criteria andWinCountBakNotIn(List<Integer> values) {
            addCriterion("win_count_bak not in", values, "winCountBak");
            return (Criteria) this;
        }

        public Criteria andWinCountBakBetween(Integer value1, Integer value2) {
            addCriterion("win_count_bak between", value1, value2, "winCountBak");
            return (Criteria) this;
        }

        public Criteria andWinCountBakNotBetween(Integer value1, Integer value2) {
            addCriterion("win_count_bak not between", value1, value2, "winCountBak");
            return (Criteria) this;
        }

        public Criteria andTotalCountBakIsNull() {
            addCriterion("total_count_bak is null");
            return (Criteria) this;
        }

        public Criteria andTotalCountBakIsNotNull() {
            addCriterion("total_count_bak is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCountBakEqualTo(Integer value) {
            addCriterion("total_count_bak =", value, "totalCountBak");
            return (Criteria) this;
        }

        public Criteria andTotalCountBakNotEqualTo(Integer value) {
            addCriterion("total_count_bak <>", value, "totalCountBak");
            return (Criteria) this;
        }

        public Criteria andTotalCountBakGreaterThan(Integer value) {
            addCriterion("total_count_bak >", value, "totalCountBak");
            return (Criteria) this;
        }

        public Criteria andTotalCountBakGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_count_bak >=", value, "totalCountBak");
            return (Criteria) this;
        }

        public Criteria andTotalCountBakLessThan(Integer value) {
            addCriterion("total_count_bak <", value, "totalCountBak");
            return (Criteria) this;
        }

        public Criteria andTotalCountBakLessThanOrEqualTo(Integer value) {
            addCriterion("total_count_bak <=", value, "totalCountBak");
            return (Criteria) this;
        }

        public Criteria andTotalCountBakIn(List<Integer> values) {
            addCriterion("total_count_bak in", values, "totalCountBak");
            return (Criteria) this;
        }

        public Criteria andTotalCountBakNotIn(List<Integer> values) {
            addCriterion("total_count_bak not in", values, "totalCountBak");
            return (Criteria) this;
        }

        public Criteria andTotalCountBakBetween(Integer value1, Integer value2) {
            addCriterion("total_count_bak between", value1, value2, "totalCountBak");
            return (Criteria) this;
        }

        public Criteria andTotalCountBakNotBetween(Integer value1, Integer value2) {
            addCriterion("total_count_bak not between", value1, value2, "totalCountBak");
            return (Criteria) this;
        }

        public Criteria andRewardLevelIsNull() {
            addCriterion("reward_level is null");
            return (Criteria) this;
        }

        public Criteria andRewardLevelIsNotNull() {
            addCriterion("reward_level is not null");
            return (Criteria) this;
        }

        public Criteria andRewardLevelEqualTo(String value) {
            addCriterion("reward_level =", value, "rewardLevel");
            return (Criteria) this;
        }

        public Criteria andRewardLevelNotEqualTo(String value) {
            addCriterion("reward_level <>", value, "rewardLevel");
            return (Criteria) this;
        }

        public Criteria andRewardLevelGreaterThan(String value) {
            addCriterion("reward_level >", value, "rewardLevel");
            return (Criteria) this;
        }

        public Criteria andRewardLevelGreaterThanOrEqualTo(String value) {
            addCriterion("reward_level >=", value, "rewardLevel");
            return (Criteria) this;
        }

        public Criteria andRewardLevelLessThan(String value) {
            addCriterion("reward_level <", value, "rewardLevel");
            return (Criteria) this;
        }

        public Criteria andRewardLevelLessThanOrEqualTo(String value) {
            addCriterion("reward_level <=", value, "rewardLevel");
            return (Criteria) this;
        }

        public Criteria andRewardLevelLike(String value) {
            addCriterion("reward_level like", value, "rewardLevel");
            return (Criteria) this;
        }

        public Criteria andRewardLevelNotLike(String value) {
            addCriterion("reward_level not like", value, "rewardLevel");
            return (Criteria) this;
        }

        public Criteria andRewardLevelIn(List<String> values) {
            addCriterion("reward_level in", values, "rewardLevel");
            return (Criteria) this;
        }

        public Criteria andRewardLevelNotIn(List<String> values) {
            addCriterion("reward_level not in", values, "rewardLevel");
            return (Criteria) this;
        }

        public Criteria andRewardLevelBetween(String value1, String value2) {
            addCriterion("reward_level between", value1, value2, "rewardLevel");
            return (Criteria) this;
        }

        public Criteria andRewardLevelNotBetween(String value1, String value2) {
            addCriterion("reward_level not between", value1, value2, "rewardLevel");
            return (Criteria) this;
        }

        public Criteria andPlayTagIdIsNull() {
            addCriterion("play_tag_id is null");
            return (Criteria) this;
        }

        public Criteria andPlayTagIdIsNotNull() {
            addCriterion("play_tag_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlayTagIdEqualTo(Integer value) {
            addCriterion("play_tag_id =", value, "playTagId");
            return (Criteria) this;
        }

        public Criteria andPlayTagIdNotEqualTo(Integer value) {
            addCriterion("play_tag_id <>", value, "playTagId");
            return (Criteria) this;
        }

        public Criteria andPlayTagIdGreaterThan(Integer value) {
            addCriterion("play_tag_id >", value, "playTagId");
            return (Criteria) this;
        }

        public Criteria andPlayTagIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("play_tag_id >=", value, "playTagId");
            return (Criteria) this;
        }

        public Criteria andPlayTagIdLessThan(Integer value) {
            addCriterion("play_tag_id <", value, "playTagId");
            return (Criteria) this;
        }

        public Criteria andPlayTagIdLessThanOrEqualTo(Integer value) {
            addCriterion("play_tag_id <=", value, "playTagId");
            return (Criteria) this;
        }

        public Criteria andPlayTagIdIn(List<Integer> values) {
            addCriterion("play_tag_id in", values, "playTagId");
            return (Criteria) this;
        }

        public Criteria andPlayTagIdNotIn(List<Integer> values) {
            addCriterion("play_tag_id not in", values, "playTagId");
            return (Criteria) this;
        }

        public Criteria andPlayTagIdBetween(Integer value1, Integer value2) {
            addCriterion("play_tag_id between", value1, value2, "playTagId");
            return (Criteria) this;
        }

        public Criteria andPlayTagIdNotBetween(Integer value1, Integer value2) {
            addCriterion("play_tag_id not between", value1, value2, "playTagId");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lottery_play_setting
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lottery_play_setting
     *
     * @mbggenerated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
