package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.AusactLotterySg;
import com.caipiao.live.common.mybatis.entity.AusactLotterySgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AusactLotterySgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ausact_lottery_sg
     *
     * @mbggenerated
     */
    int countByExample(AusactLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ausact_lottery_sg
     *
     * @mbggenerated
     */
    int deleteByExample(AusactLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ausact_lottery_sg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ausact_lottery_sg
     *
     * @mbggenerated
     */
    int insert(AusactLotterySg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ausact_lottery_sg
     *
     * @mbggenerated
     */
    int insertSelective(AusactLotterySg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ausact_lottery_sg
     *
     * @mbggenerated
     */
    AusactLotterySg selectOneByExample(AusactLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ausact_lottery_sg
     *
     * @mbggenerated
     */
    List<AusactLotterySg> selectByExample(AusactLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ausact_lottery_sg
     *
     * @mbggenerated
     */
    AusactLotterySg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ausact_lottery_sg
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AusactLotterySg record, @Param("example") AusactLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ausact_lottery_sg
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AusactLotterySg record, @Param("example") AusactLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ausact_lottery_sg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AusactLotterySg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ausact_lottery_sg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AusactLotterySg record);
}
