package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.AuspksKillNumber;
import com.caipiao.live.common.mybatis.entity.AuspksKillNumberExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AuspksKillNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auspks_kill_number
     *
     * @mbggenerated
     */
    int countByExample(AuspksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auspks_kill_number
     *
     * @mbggenerated
     */
    int deleteByExample(AuspksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auspks_kill_number
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auspks_kill_number
     *
     * @mbggenerated
     */
    int insert(AuspksKillNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auspks_kill_number
     *
     * @mbggenerated
     */
    int insertSelective(AuspksKillNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auspks_kill_number
     *
     * @mbggenerated
     */
    AuspksKillNumber selectOneByExample(AuspksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auspks_kill_number
     *
     * @mbggenerated
     */
    List<AuspksKillNumber> selectByExample(AuspksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auspks_kill_number
     *
     * @mbggenerated
     */
    AuspksKillNumber selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auspks_kill_number
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AuspksKillNumber record, @Param("example") AuspksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auspks_kill_number
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AuspksKillNumber record, @Param("example") AuspksKillNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auspks_kill_number
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuspksKillNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auspks_kill_number
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuspksKillNumber record);
}
