package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.CptOpenMember;
import com.caipiao.live.common.mybatis.entity.CptOpenMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CptOpenMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    int countByExample(CptOpenMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    int deleteByExample(CptOpenMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    int insert(CptOpenMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    int insertSelective(CptOpenMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    CptOpenMember selectOneByExample(CptOpenMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    List<CptOpenMember> selectByExample(CptOpenMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    CptOpenMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CptOpenMember record, @Param("example") CptOpenMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CptOpenMember record, @Param("example") CptOpenMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CptOpenMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CptOpenMember record);
}
