package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.DbBetOrder;
import com.caipiao.live.common.mybatis.entity.DbBetOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbBetOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bet_order
     *
     * @mbggenerated
     */
    int countByExample(DbBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bet_order
     *
     * @mbggenerated
     */
    int deleteByExample(DbBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bet_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bet_order
     *
     * @mbggenerated
     */
    int insert(DbBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bet_order
     *
     * @mbggenerated
     */
    int insertSelective(DbBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bet_order
     *
     * @mbggenerated
     */
    DbBetOrder selectOneByExample(DbBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bet_order
     *
     * @mbggenerated
     */
    List<DbBetOrder> selectByExample(DbBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bet_order
     *
     * @mbggenerated
     */
    DbBetOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bet_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DbBetOrder record, @Param("example") DbBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bet_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DbBetOrder record, @Param("example") DbBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bet_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DbBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_bet_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DbBetOrder record);
}
