package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.JsbjpksCountSgds;
import com.caipiao.live.common.mybatis.entity.JsbjpksCountSgdsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JsbjpksCountSgdsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsbjpks_count_sgds
     *
     * @mbggenerated
     */
    int countByExample(JsbjpksCountSgdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsbjpks_count_sgds
     *
     * @mbggenerated
     */
    int deleteByExample(JsbjpksCountSgdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsbjpks_count_sgds
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsbjpks_count_sgds
     *
     * @mbggenerated
     */
    int insert(JsbjpksCountSgds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsbjpks_count_sgds
     *
     * @mbggenerated
     */
    int insertSelective(JsbjpksCountSgds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsbjpks_count_sgds
     *
     * @mbggenerated
     */
    JsbjpksCountSgds selectOneByExample(JsbjpksCountSgdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsbjpks_count_sgds
     *
     * @mbggenerated
     */
    List<JsbjpksCountSgds> selectByExample(JsbjpksCountSgdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsbjpks_count_sgds
     *
     * @mbggenerated
     */
    JsbjpksCountSgds selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsbjpks_count_sgds
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JsbjpksCountSgds record, @Param("example") JsbjpksCountSgdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsbjpks_count_sgds
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JsbjpksCountSgds record, @Param("example") JsbjpksCountSgdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsbjpks_count_sgds
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JsbjpksCountSgds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsbjpks_count_sgds
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JsbjpksCountSgds record);
}
