package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.OrderBetRecord;
import com.caipiao.live.common.mybatis.entity.OrderBetRecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderBetRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bet_record
     *
     * @mbggenerated
     */
    int countByExample(OrderBetRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bet_record
     *
     * @mbggenerated
     */
    int deleteByExample(OrderBetRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bet_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bet_record
     *
     * @mbggenerated
     */
    int insert(OrderBetRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bet_record
     *
     * @mbggenerated
     */
    int insertSelective(OrderBetRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bet_record
     *
     * @mbggenerated
     */
    OrderBetRecord selectOneByExample(OrderBetRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bet_record
     *
     * @mbggenerated
     */
    List<OrderBetRecord> selectByExample(OrderBetRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bet_record
     *
     * @mbggenerated
     */
    OrderBetRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bet_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderBetRecord record, @Param("example") OrderBetRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bet_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderBetRecord record, @Param("example") OrderBetRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bet_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderBetRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bet_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderBetRecord record);
}
