package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.OrderAppendRecord;
import com.caipiao.live.common.mybatis.entity.OrderAppendRecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderAppendRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_append_record
     *
     * @mbggenerated
     */
    int countByExample(OrderAppendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_append_record
     *
     * @mbggenerated
     */
    int deleteByExample(OrderAppendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_append_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_append_record
     *
     * @mbggenerated
     */
    int insert(OrderAppendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_append_record
     *
     * @mbggenerated
     */
    int insertSelective(OrderAppendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_append_record
     *
     * @mbggenerated
     */
    OrderAppendRecord selectOneByExample(OrderAppendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_append_record
     *
     * @mbggenerated
     */
    List<OrderAppendRecord> selectByExample(OrderAppendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_append_record
     *
     * @mbggenerated
     */
    OrderAppendRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_append_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderAppendRecord record, @Param("example") OrderAppendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_append_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderAppendRecord record, @Param("example") OrderAppendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_append_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderAppendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_append_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderAppendRecord record);
}
