//package com.caipiao.live.common.mybatis.mapper;
//
//import com.caipiao.live.common.mybatis.entity.QuickSscorder;
//import com.caipiao.live.common.mybatis.entity.QuickSscorderExample;
//import java.util.List;
//import org.apache.ibatis.annotations.Param;
//
//public interface QuickSscorderMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table quick_sscorder
//     *
//     * @mbggenerated
//     */
//    int countByExample(QuickSscorderExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table quick_sscorder
//     *
//     * @mbggenerated
//     */
//    int deleteByExample(QuickSscorderExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table quick_sscorder
//     *
//     * @mbggenerated
//     */
//    int deleteByPrimaryKey(Long ksorderid);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table quick_sscorder
//     *
//     * @mbggenerated
//     */
//    int insert(QuickSscorder record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table quick_sscorder
//     *
//     * @mbggenerated
//     */
//    int insertSelective(QuickSscorder record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table quick_sscorder
//     *
//     * @mbggenerated
//     */
//    QuickSscorder selectOneByExample(QuickSscorderExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table quick_sscorder
//     *
//     * @mbggenerated
//     */
//    List<QuickSscorder> selectByExample(QuickSscorderExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table quick_sscorder
//     *
//     * @mbggenerated
//     */
//    QuickSscorder selectByPrimaryKey(Long ksorderid);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table quick_sscorder
//     *
//     * @mbggenerated
//     */
//    int updateByExampleSelective(@Param("record") QuickSscorder record, @Param("example") QuickSscorderExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table quick_sscorder
//     *
//     * @mbggenerated
//     */
//    int updateByExample(@Param("record") QuickSscorder record, @Param("example") QuickSscorderExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table quick_sscorder
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKeySelective(QuickSscorder record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table quick_sscorder
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKey(QuickSscorder record);
//}
