package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.ReturnLotterySet;
import com.caipiao.live.common.mybatis.entity.ReturnLotterySetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReturnLotterySetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_lottery_set
     *
     * @mbggenerated
     */
    int countByExample(ReturnLotterySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_lottery_set
     *
     * @mbggenerated
     */
    int deleteByExample(ReturnLotterySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_lottery_set
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_lottery_set
     *
     * @mbggenerated
     */
    int insert(ReturnLotterySet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_lottery_set
     *
     * @mbggenerated
     */
    int insertSelective(ReturnLotterySet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_lottery_set
     *
     * @mbggenerated
     */
    ReturnLotterySet selectOneByExample(ReturnLotterySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_lottery_set
     *
     * @mbggenerated
     */
    List<ReturnLotterySet> selectByExample(ReturnLotterySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_lottery_set
     *
     * @mbggenerated
     */
    ReturnLotterySet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_lottery_set
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReturnLotterySet record, @Param("example") ReturnLotterySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_lottery_set
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReturnLotterySet record, @Param("example") ReturnLotterySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_lottery_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReturnLotterySet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_lottery_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReturnLotterySet record);
}
