package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.SscPlaySetting;
import com.caipiao.live.common.mybatis.entity.SscPlaySettingExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SscPlaySettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_play_setting
     *
     * @mbggenerated
     */
    int countByExample(SscPlaySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_play_setting
     *
     * @mbggenerated
     */
    int deleteByExample(SscPlaySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_play_setting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_play_setting
     *
     * @mbggenerated
     */
    int insert(SscPlaySetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_play_setting
     *
     * @mbggenerated
     */
    int insertSelective(SscPlaySetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_play_setting
     *
     * @mbggenerated
     */
    SscPlaySetting selectOneByExample(SscPlaySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_play_setting
     *
     * @mbggenerated
     */
    List<SscPlaySetting> selectByExample(SscPlaySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_play_setting
     *
     * @mbggenerated
     */
    SscPlaySetting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_play_setting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SscPlaySetting record, @Param("example") SscPlaySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_play_setting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SscPlaySetting record, @Param("example") SscPlaySettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_play_setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SscPlaySetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssc_play_setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SscPlaySetting record);
}
