package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.SysParameter;
import com.caipiao.live.common.mybatis.entity.SysParameterExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbg.generated Tue Oct 26 17:00:28 ICT 2021
     */
    long countByExample(SysParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbg.generated Tue Oct 26 17:00:28 ICT 2021
     */
    int deleteByExample(SysParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbg.generated Tue Oct 26 17:00:28 ICT 2021
     */
    int deleteByPrimaryKey(Long paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbg.generated Tue Oct 26 17:00:28 ICT 2021
     */
    int insert(SysParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbg.generated Tue Oct 26 17:00:28 ICT 2021
     */
    int insertSelective(SysParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbg.generated Tue Oct 26 17:00:28 ICT 2021
     */
    List<SysParameter> selectByExample(SysParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbg.generated Tue Oct 26 17:00:28 ICT 2021
     */
    SysParameter selectByPrimaryKey(Long paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbg.generated Tue Oct 26 17:00:28 ICT 2021
     */
    int updateByExampleSelective(@Param("record") SysParameter record, @Param("example") SysParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbg.generated Tue Oct 26 17:00:28 ICT 2021
     */
    int updateByExample(@Param("record") SysParameter record, @Param("example") SysParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbg.generated Tue Oct 26 17:00:28 ICT 2021
     */
    int updateByPrimaryKeySelective(SysParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbg.generated Tue Oct 26 17:00:28 ICT 2021
     */
    int updateByPrimaryKey(SysParameter record);
}