package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.TcdltLotterySg;
import com.caipiao.live.common.mybatis.entity.TcdltLotterySgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TcdltLotterySgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcdlt_lottery_sg
     *
     * @mbggenerated
     */
    int countByExample(TcdltLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcdlt_lottery_sg
     *
     * @mbggenerated
     */
    int deleteByExample(TcdltLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcdlt_lottery_sg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcdlt_lottery_sg
     *
     * @mbggenerated
     */
    int insert(TcdltLotterySg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcdlt_lottery_sg
     *
     * @mbggenerated
     */
    int insertSelective(TcdltLotterySg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcdlt_lottery_sg
     *
     * @mbggenerated
     */
    TcdltLotterySg selectOneByExample(TcdltLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcdlt_lottery_sg
     *
     * @mbggenerated
     */
    List<TcdltLotterySg> selectByExample(TcdltLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcdlt_lottery_sg
     *
     * @mbggenerated
     */
    TcdltLotterySg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcdlt_lottery_sg
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TcdltLotterySg record, @Param("example") TcdltLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcdlt_lottery_sg
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TcdltLotterySg record, @Param("example") TcdltLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcdlt_lottery_sg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TcdltLotterySg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcdlt_lottery_sg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TcdltLotterySg record);
}
