package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.TenbjpksCountSglh;
import com.caipiao.live.common.mybatis.entity.TenbjpksCountSglhExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TenbjpksCountSglhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbjpks_count_sglh
     *
     * @mbggenerated
     */
    int countByExample(TenbjpksCountSglhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbjpks_count_sglh
     *
     * @mbggenerated
     */
    int deleteByExample(TenbjpksCountSglhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbjpks_count_sglh
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbjpks_count_sglh
     *
     * @mbggenerated
     */
    int insert(TenbjpksCountSglh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbjpks_count_sglh
     *
     * @mbggenerated
     */
    int insertSelective(TenbjpksCountSglh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbjpks_count_sglh
     *
     * @mbggenerated
     */
    TenbjpksCountSglh selectOneByExample(TenbjpksCountSglhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbjpks_count_sglh
     *
     * @mbggenerated
     */
    List<TenbjpksCountSglh> selectByExample(TenbjpksCountSglhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbjpks_count_sglh
     *
     * @mbggenerated
     */
    TenbjpksCountSglh selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbjpks_count_sglh
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TenbjpksCountSglh record, @Param("example") TenbjpksCountSglhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbjpks_count_sglh
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TenbjpksCountSglh record, @Param("example") TenbjpksCountSglhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbjpks_count_sglh
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TenbjpksCountSglh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbjpks_count_sglh
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TenbjpksCountSglh record);
}
