package com.caipiao.live.common.mybatis.mapper;

import com.caipiao.live.common.mybatis.entity.XjplhcLotterySg;
import com.caipiao.live.common.mybatis.entity.XjplhcLotterySgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XjplhcLotterySgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xjplhc_lottery_sg
     *
     * @mbggenerated
     */
    int countByExample(XjplhcLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xjplhc_lottery_sg
     *
     * @mbggenerated
     */
    int deleteByExample(XjplhcLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xjplhc_lottery_sg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xjplhc_lottery_sg
     *
     * @mbggenerated
     */
    int insert(XjplhcLotterySg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xjplhc_lottery_sg
     *
     * @mbggenerated
     */
    int insertSelective(XjplhcLotterySg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xjplhc_lottery_sg
     *
     * @mbggenerated
     */
    XjplhcLotterySg selectOneByExample(XjplhcLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xjplhc_lottery_sg
     *
     * @mbggenerated
     */
    List<XjplhcLotterySg> selectByExample(XjplhcLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xjplhc_lottery_sg
     *
     * @mbggenerated
     */
    XjplhcLotterySg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xjplhc_lottery_sg
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") XjplhcLotterySg record, @Param("example") XjplhcLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xjplhc_lottery_sg
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") XjplhcLotterySg record, @Param("example") XjplhcLotterySgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xjplhc_lottery_sg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XjplhcLotterySg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xjplhc_lottery_sg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XjplhcLotterySg record);
}
